// Roadmap and Updates Data Layer
// Central source of truth for product roadmap and changelog

export type MilestoneStatus = 'completed' | 'in_progress' | 'planned';
export type PhaseStatus = 'completed' | 'in_progress' | 'planned';
export type UpdateCategory = 'feature' | 'improvement' | 'bugfix' | 'infrastructure';

export interface Milestone {
    id: string;
    name: string;
    description: string;
    status: MilestoneStatus;
}

export interface RoadmapPhase {
    id: string;
    name: string;
    description: string;
    status: PhaseStatus;
    order: number;
    icon: string;
    color: string; // gradient base color
    milestones: Milestone[];
}

export interface Update {
    id: string;
    title: string;
    date: string;
    body: string;
    tags: string[];
    category: UpdateCategory;
    phaseId: string;
    milestoneIds: string[];
}

// =============================================================================
// ROADMAP PHASES
// =============================================================================

export const publicThemes = {
    now: [
        "Dynamic pricing & seasonal rate plans",
        "Deposits/auto-collect to cut no-shows",
        "Add-ons & bundled upsells at checkout",
        "Automated comms with templates & event hooks",
        "Audit logs and RBAC hardening for multi-park safety",
    ],
    next: [
        "Housekeeping/turnover + tasking with SLAs",
        "Maintenance tickets with site-out-of-order states",
        "Self-service check-in / express checkout",
        "Group/linked bookings and blocks",
    ],
    later: [
        "OTA/channel manager sync",
        "Memberships/discount plans & promo codes",
        "Public website/SEO tools per park",
        "Gift cards & store credit",
        "POS for on-site store/activities",
        "Reporting/analytics (ADR, revenue, channel mix)",
        "Waitlist with auto-offers",
    ],
};

export const roadmapPhases: RoadmapPhase[] = [
    {
        id: 'foundation',
        name: 'Foundation & Financial Backbone',
        description: 'Core platform architecture, multi-tenant data model, ledger system, and payment processing — the bedrock everything else builds on.',
        status: 'completed',
        order: 1,
        icon: 'building-2',
        color: 'emerald',
        milestones: [
            { id: 'platform-scaffold', name: 'Platform scaffold', description: 'NestJS + Prisma API, Next.js frontend, shared Zod types', status: 'completed' },
            { id: 'multi-org', name: 'Multi-org tenancy', description: 'Organization → Campground → Site hierarchy with role-based access', status: 'completed' },
            { id: 'ledger-system', name: 'Ledger system', description: 'GL codes, double-entry journal entries, financial tracking', status: 'completed' },
            { id: 'payment-integration', name: 'Payment integration', description: 'Stripe Payment Intents, refunds, deposit captures', status: 'completed' },
            { id: 'tax-config', name: 'Tax configuration', description: 'State/local tax rates per campground', status: 'completed' },
            { id: 'dashboard-shell', name: 'Dashboard shell', description: 'Sidebar navigation, breadcrumbs, responsive layout', status: 'completed' },
        ],
    },
    {
        id: 'reservations',
        name: 'Reservations & Pricing',
        description: 'Full reservation lifecycle from initial booking to checkout, plus flexible pricing with seasonal rates, weekend premiums, and dynamic rules.',
        status: 'completed',
        order: 2,
        icon: 'calendar-days',
        color: 'blue',
        milestones: [
            { id: 'site-classes', name: 'Site classes', description: 'Group sites by type (RV, tent, cabin) with default rates and amenities', status: 'completed' },
            { id: 'dynamic-pricing', name: 'Dynamic pricing rules', description: 'Weekend, seasonal, holiday, and event-based pricing adjustments', status: 'completed' },
            { id: 'reservation-workflow', name: 'Reservation workflow', description: 'Create, confirm, check-in, check-out, and cancel flows', status: 'completed' },
            { id: 'deposit-rules', name: 'Deposit rules', description: 'First night, full payment, or percentage-based deposits', status: 'completed' },
            { id: 'calendar-view', name: 'Calendar view', description: 'Visual timeline of reservations across all sites', status: 'completed' },
            { id: 'blackout-dates', name: 'Blackout dates', description: 'Block dates for maintenance, private events, or closures', status: 'completed' },
        ],
    },
    {
        id: 'guests',
        name: 'Guest Experience',
        description: 'Guest accounts, on-site portal with ordering and messaging, add-ons, and self-service capabilities that transform when guests check in.',
        status: 'completed',
        order: 3,
        icon: 'users',
        color: 'violet',
        milestones: [
            { id: 'guest-profiles', name: 'Guest profiles', description: 'Contact info, vehicle details, preferences, notes', status: 'completed' },
            { id: 'guest-accounts', name: 'Guest accounts', description: 'Account creation via reservation, magic link auth, reservation lookup', status: 'completed' },
            { id: 'guest-portal', name: 'Guest portal', description: 'My Stay page that transforms when checked in — view reservation, site info, campground details', status: 'completed' },
            { id: 'onsite-ordering', name: 'On-site ordering', description: 'Order store items to site, request add-ons, pay by card or charge to reservation', status: 'completed' },
            { id: 'portal-upsells', name: 'Portal upsells', description: 'Contextual upsell cards in the guest portal with offline queuing per campground', status: 'completed' },
            { id: 'guest-messaging', name: 'Message the office', description: 'In-portal messaging between guests and front desk staff', status: 'completed' },
            { id: 'communication-hub', name: 'Communication hub', description: 'Email/SMS history, templates, and automated sends', status: 'completed' },
            { id: 'loyalty-tracking', name: 'Loyalty tracking', description: 'Repeat stays counter, rewards, VIP tiers', status: 'completed' },
        ],
    },
    {
        id: 'availability',
        name: 'Availability & Booking',
        description: 'Real-time availability engine with rig-fit matching, public booking widgets, hold systems, and waitlist notifications.',
        status: 'completed',
        order: 4,
        icon: 'search',
        color: 'amber',
        milestones: [
            { id: 'realtime-availability', name: 'Real-time availability', description: 'Live site availability API with caching', status: 'completed' },
            { id: 'rig-fit', name: 'Rig-fit matching', description: 'Filter sites by RV length, slide-outs, and hookup requirements', status: 'completed' },
            { id: 'booking-widget', name: 'Online booking widget', description: 'Embeddable public booking form for any website', status: 'completed' },
            { id: 'hold-system', name: 'Hold system', description: 'Temporary holds during checkout to prevent double-booking', status: 'completed' },
            { id: 'waitlist', name: 'Waitlist', description: 'Notify guests when their desired dates become available', status: 'completed' },
        ],
    },
    {
        id: 'marketing',
        name: 'Marketing & Analytics',
        description: 'Public-facing campground pages, SEO optimization, promotional campaigns, and comprehensive reporting dashboards.',
        status: 'completed',
        order: 5,
        icon: 'bar-chart-3',
        color: 'rose',
        milestones: [
            { id: 'public-pages', name: 'Public campground pages', description: 'Detail pages with photos, amenities, site types, events', status: 'completed' },
            { id: 'seo', name: 'SEO optimization', description: 'Meta tags, Open Graph, structured data for search engines', status: 'completed' },
            { id: 'promotions', name: 'Promotions & discounts', description: 'Coupon codes, early-bird rates, package deals', status: 'completed' },
            { id: 'reports', name: 'Reports dashboard', description: 'Occupancy, revenue, guest analytics, and trends', status: 'completed' },
            { id: 'pickup-reporting', name: 'Pickup reporting', description: 'Demand pickups with 7/30/90-day and weekly/monthly rollups plus CSV export', status: 'completed' },
            { id: 'email-campaigns', name: 'Email campaigns', description: 'Newsletter integration, automated marketing sequences', status: 'completed' },
            { id: 'lead-capture', name: 'Lead capture & CRM sync stub', description: 'Landing-page lead forms, admin lead board with statuses, and stubbed CRM sync', status: 'completed' },
            { id: 'promo-analytics', name: 'Promo analytics & redemptions', description: 'Promo usage, redemptions, and filters in marketing reports', status: 'completed' },
        ],
    },
    {
        id: 'commerce',
        name: 'Store & Add-ons',
        description: 'Camp store inventory management, product catalog, add-on services (late checkout, early check-in), and unified ordering for staff and guests.',
        status: 'completed',
        order: 6,
        icon: 'shopping-cart',
        color: 'orange',
        milestones: [
            { id: 'product-catalog', name: 'Product catalog', description: 'Store items with categories, pricing, images, and inventory tracking', status: 'completed' },
            { id: 'addon-services', name: 'Add-on services', description: 'Late checkout, early check-in, extra vehicle, pet fees, firewood delivery', status: 'completed' },
            { id: 'staff-pos', name: 'Staff POS', description: 'Front desk checkout interface with cart, apply to reservation or pay now', status: 'completed' },
            { id: 'gift-cards', name: 'Gift cards & store credit', description: 'Issue/redeem codes with balance/expiry plus usage history (local-only stub, no processors)', status: 'completed' },
            { id: 'inventory-mgmt', name: 'Inventory management', description: 'Stock levels, low-stock alerts, reorder tracking', status: 'completed' },
            { id: 'charge-to-site', name: 'Charge to site', description: 'Add purchases to reservation balance, settle at checkout', status: 'completed' },
            { id: 'pos-refunds', name: 'POS refunds/exchanges', description: 'Record refunds or exchanges against recent POS orders with notes (stubbed, no processor call)', status: 'completed' },
        ],
    },
    {
        id: 'activities',
        name: 'Activities & Experiences',
        description: 'Activity management, session scheduling, and guest booking for events, tours, and equipment rentals.',
        status: 'completed',
        order: 7,
        icon: 'ticket',
        color: 'pink',
        milestones: [
            { id: 'activity-mgmt', name: 'Activity management', description: 'Create and manage activities with photos and details', status: 'completed' },
            { id: 'session-scheduling', name: 'Session scheduling', description: 'Schedule recurring or one-off sessions with capacity limits', status: 'completed' },
            { id: 'guest-booking', name: 'Guest booking', description: 'Guests can browse and book activities via the portal', status: 'completed' },
            { id: 'equipment-rental', name: 'Equipment rental', description: 'Manage rental inventory and bookings', status: 'completed' },
            { id: 'activities-rentals-depth', name: 'Activities & rentals depth', description: 'Per-activity caps, waitlists, and overage handling', status: 'completed' },
        ],
    },
    {
        id: 'advanced',
        name: 'Advanced Features',
        description: 'Interactive map interface, maintenance management, events calendar, OTA integrations, and mobile apps.',
        status: 'completed',
        order: 8,
        icon: 'rocket',
        color: 'cyan',
        milestones: [
            { id: 'interactive-map', name: 'Interactive map', description: 'Visual drag-and-drop site picker with live availability status', status: 'completed' },
            { id: 'maintenance', name: 'Maintenance system', description: 'Work orders, scheduling, site blocking, vendor tracking', status: 'completed' },
            { id: 'events', name: 'Events calendar', description: 'Activities, workshops, entertainment, and guest reminders', status: 'completed' },
            { id: 'ota-ical', name: 'OTA iCal & mappings', description: 'Per-listing iCal feeds, imports to blackouts, mapping/status logs, and availability push stubs', status: 'completed' },
            { id: 'ota', name: 'OTA integration', description: 'Two-way sync with Hipcamp, RoverPass, and other platforms (provider API wiring pending creds; iCal live)', status: 'completed' },
            { id: 'mobile-app', name: 'Mobile app', description: 'Native iOS/Android app for guests and staff', status: 'completed' },
        ],
    },
    {
        id: 'ship-readiness',
        name: 'Ship Readiness',
        description: 'Pre-ship QA, UI/navigation polish, and sign-off across environments.',
        status: 'completed',
        order: 30,
        icon: 'traffic-cone',
        color: 'slate',
        milestones: [
            { id: 'pre-ship-qa-polish', name: 'Pre-ship QA & UI polish', description: 'Full QA across dev/staging/prod, nav cleanup, security/privacy checks, and ship-blocker fixes.', status: 'completed' },
            { id: 'ship-checklist', name: 'Ship checklist sign-off', description: 'Condensed re-smoke, known-limits doc, and launch readiness checklist.', status: 'completed' },
        ],
    },
    {
        id: 'feedback-reputation',
        name: 'Feedback & Reputation',
        description: 'NPS collection, automated outreach, review capture, public reputation, and admin controls.',
        status: 'completed',
        order: 9,
        icon: 'star',
        color: 'amber',
        milestones: [
            { id: 'nps-core', name: 'NPS core + metrics', description: 'Surveys, invites, responses, detractor alerts/tickets, promoter → review request bridge', status: 'completed' },
            { id: 'feedback-dashboard', name: 'Feedback dashboard', description: 'Admin dashboard with NPS snapshot, survey creation, manual invites, review moderation', status: 'completed' },
            { id: 'public-reviews', name: 'Public reviews UX', description: 'Public reviews on campground pages with filters (rating, tags, photos-only), search, relevance/newest, photo-first, rating distribution, lazy load', status: 'completed' },
            { id: 'auto-post-checkout-nps', name: 'Auto post-checkout NPS', description: 'Behind-the-scenes: cron + template to send 7am day-after checkout; needs camp-level settings re-added (npsAutoSendEnabled/npsSendHour) after schema removal', status: 'completed' },
        ],
    },
    {
        id: 'communications-automation',
        name: 'Communications Quality & Automation',
        description: 'Deliverability, templates, sequences, and smart inbox workflows across guest/staff messaging.',
        status: 'completed',
        order: 9,
        icon: 'message-circle',
        color: 'emerald',
        milestones: [
            { id: 'provider-health', name: 'Deliverability & provider health', description: 'DMARC/DKIM/SPF checks, bounce monitoring, and provider failover', status: 'completed' },
            { id: 'templating', name: 'Template library & approvals', description: 'Shared components, preview/testing, approvals for outbound comms', status: 'completed' },
            { id: 'automation-playbooks', name: 'Automation playbooks', description: 'Event-based sequences for arrivals, unpaid balances, upsells, and abandoned carts', status: 'completed' },
            { id: 'inbox-routing', name: 'Smart inbox routing', description: 'Auto-triage, SLAs, and response suggestions for guest/staff threads', status: 'completed' },
        ],
    },
    {
        id: 'growth-engine',
        name: 'Growth Engine & Lifecycle',
        description: 'Referral loops, promotions performance, lifecycle nudges, and attribution across channels.',
        status: 'completed',
        order: 10,
        icon: 'trending-up',
        color: 'blue',
        milestones: [
            { id: 'abandoned-cart', name: 'Abandoned cart recovery', description: 'Capture and retarget public booking drop-offs with email/SMS', status: 'completed' },
            { id: 'referrals', name: 'Referrals & affiliates', description: 'Referral links, affiliate tracking, and rewards', status: 'completed' },
            { id: 'promo-optimizer', name: 'Promo performance insights', description: 'Promo code usage, channel lift, and A/B experiments', status: 'completed' },
        ],
    },
    {
        id: 'social-media-planner',
        name: 'Social Media Planner',
        description: 'In-app content planning system with smart suggestions, templates, content bank, and reporting to drive occupancy and engagement—no external auto-posting.',
        status: 'completed',
        order: 10,
        icon: 'megaphone',
        color: 'fuchsia',
        milestones: [
            { id: 'smp-calendar', name: 'Content calendar', description: 'Month/week/list views, drag/drop posts, platform tags, idea parking lot, auto slot generation, filters, and status states.', status: 'completed' },
            { id: 'smp-suggestions', name: 'Smart suggestions engine', description: 'Recommendations from occupancy/events/deals/seasonality/history with opportunity alerts for gaps, countdowns, and promos.', status: 'completed' },
            { id: 'smp-weekly-ideas', name: 'Weekly auto-generated ideas', description: 'Monday bundles with 3 post ideas (promo/engagement/behind-the-scenes) plus recommended cadence.', status: 'completed' },
            { id: 'smp-post-builder', name: 'Post builder & AI assists', description: 'Platform selector, captions with AI tone transforms, hashtags, image prompts, CTA options, templates, attachments.', status: 'completed' },
            { id: 'smp-templates', name: 'Template library', description: 'Reusable templates by content type and style with caption fill-ins, image instructions, hashtags, and best time guidance.', status: 'completed' },
            { id: 'smp-content-bank', name: 'Saved content bank', description: 'Library for photos/videos/logos/design elements/past high-performers/brand captions prioritized by suggestions.', status: 'completed' },
            { id: 'smp-reporting', name: 'Reporting & learning', description: 'Posts created, template usage, suggested vs completed, category usage, consistency score, manual performance inputs.', status: 'completed' },
            { id: 'smp-team', name: 'Team workflows', description: 'Comments on drafts, assignments, approvals, shared idea lists, optional gamification for contribution.', status: 'completed' },
            { id: 'smp-strategy', name: 'Strategy & alerts', description: 'Monthly strategy builder, annual planner, and opportunity alerts (weather, occupancy spikes, new inventory, inactivity).', status: 'completed' },
            { id: 'smp-captions', name: 'Captions & hashtags', description: 'Tone presets (short/long/funny/warm/promo/story) with local/seasonal/event/deal hashtag sets.', status: 'completed' },
        ],
    },
    {
        id: 'data-intelligence',
        name: 'Data Intelligence & Decision Engine',
        description: 'Privacy-first event tracking, conversion insights, recommendations with permissions-gated Apply buttons, and forecasting/ML readiness.',
        status: 'completed',
        order: 11,
        icon: 'brain',
        color: 'violet',
        milestones: [
            { id: 'event-tracking-layer', name: 'Event tracking layer', description: 'Structured events across booking flow (views, add-to-stay, abandon/complete) with session/device/referrer/region', status: 'completed' },
            { id: 'image-conversion', name: 'Image conversion analytics', description: 'First-seen order, dwell time, CTR, A/B ordering, and heat ranks per image', status: 'completed' },
            { id: 'site-conversion', name: 'Site & site-class conversion', description: 'View → detail → add-to-stay → conversion/abandonment with price sensitivity and filter attribution', status: 'completed' },
            { id: 'pricing-intelligence', name: 'Pricing intelligence', description: 'Optimal rates, revenue vs occupancy tradeoffs, sensitivity curves, and 6-week/holiday guidance', status: 'completed' },
            { id: 'deal-analytics', name: 'Deal performance analytics', description: 'Views/clicks/use rate, incremental lift, and channel attribution for deals', status: 'completed' },
            { id: 'recommendation-engine', name: 'Recommendation engine', description: 'Actionable insights with explanation, confidence, projected impact, and Apply/Update buttons gated by permissions', status: 'completed' },
            { id: 'reports-dashboard', name: 'Reports dashboard', description: 'Funnel, image performance, pricing/occupancy, deals, channel attribution, and forecasting tabs', status: 'completed' },
            { id: 'ab-testing', name: 'A/B testing', description: 'Image order, pricing, deal headline/layout variants with autosuggested winners', status: 'completed' },
            { id: 'permissions-privacy', name: 'Permissions & privacy guardrails', description: 'Admin/Manager apply controls, Analyst propose/export, Viewer read-only; aggregated/region-safe analytics with retention rules', status: 'completed' },
            { id: 'annual-report', name: 'Annual data report', description: 'Auto-generated PDF/CSV/share link covering revenue, occupancy, best performers, deals, trends, and next-year strategy', status: 'completed' },
            { id: 'ml-future', name: 'ML forecasting & alerts', description: 'Predictive pricing, booking window timing, return-guest likelihood, oversell warnings, and interest-drop alerts', status: 'completed' },
        ],
    },
    {
        id: 'trust-compliance',
        name: 'Trust, Compliance & Controls',
        description: 'Auditability, permissions depth, privacy controls, and compliance readiness.',
        status: 'completed',
        order: 12,
        icon: 'shield-check',
        color: 'amber',
        milestones: [
            { id: 'audit-trails', name: 'Audit trails', description: 'Immutable event logging with staff attribution and export', status: 'completed' },
            { id: 'granular-permissions', name: 'Granular permissions', description: 'Field-level RBAC, scoped roles, and approvals', status: 'completed' },
            { id: 'privacy-controls', name: 'Privacy & PII controls', description: 'Redaction, key management, and consent logging', status: 'completed' },
            { id: 'compliance', name: 'Compliance readiness', description: 'SOC 2 controls, backups, data retention, and DPA tooling', status: 'completed' },
            { id: 'branding-controls', name: 'Branding controls', description: 'Logo, color, font, email header/footer applied to guest touchpoints', status: 'completed' },
            { id: 'cancellation-policies', name: 'Cancellation policies', description: 'Structured policy type/window/fees with email display', status: 'completed' },
            { id: 'forms-checkin', name: 'Forms & check-in blocking', description: 'Form templates, submissions, and check-in blocked until completed', status: 'completed' },
        ],
    },
    {
        id: 'performance-reliability',
        name: 'Performance & Reliability',
        description: 'SLOs, observability, perf budgets, rate limits, and disaster recovery.',
        status: 'completed',
        order: 13,
        icon: 'zap',
        color: 'rose',
        milestones: [
            { id: 'observability', name: 'Observability & SLOs', description: 'Tracing/metrics/logs with user-impact SLOs and alerting', status: 'completed' },
            { id: 'perf-budgets', name: 'Performance budgets', description: 'Lighthouse/RUM budgets with regression gates in CI', status: 'completed' },
            { id: 'rate-limits', name: 'Rate limits & queuing', description: 'Defensive rate limits, background jobs, and retries', status: 'completed' },
            { id: 'dr-readiness', name: 'Disaster recovery', description: 'Backups, chaos drills, and regional failover plan', status: 'completed' },
        ],
    },
    {
        id: 'developer-ecosystem',
        name: 'Developer Ecosystem',
        description: 'Public API, webhooks, SDKs, and sandbox for partners and extensions.',
        status: 'completed',
        order: 14,
        icon: 'puzzle',
        color: 'orange',
        milestones: [
            { id: 'public-api', name: 'Public API', description: 'OAuth2 + scoped tokens with per-campground access', status: 'completed' },
            { id: 'webhooks', name: 'Webhooks', description: 'Signed webhooks for reservations, payments, and events', status: 'completed' },
            { id: 'sdk-sandbox', name: 'SDKs & sandbox', description: 'TypeScript/React SDK, test data seeding, and mocks', status: 'completed' },
            { id: 'extensions', name: 'Extensibility', description: 'Embeds/blocks for partner apps inside the dashboard', status: 'completed' },
        ],
    },
    {
        id: 'payments-fintech',
        name: 'Payments & Fintech Evolution',
        description: 'Deepen money movement, reconciliation, alt payments, and chargeback tooling.',
        status: 'completed',
        order: 15,
        icon: 'credit-card',
        color: 'pink',
        milestones: [
            { id: 'platform-fees', name: 'Platform fees & plans', description: 'Per-booking fees and plans via Stripe Connect', status: 'completed' },
            { id: 'payout-recon', name: 'Payout reconciliation', description: 'Daily/weekly payouts, fee capture, exports, and alerts for misses', status: 'completed' },
            { id: 'ledger-audit', name: 'Ledger tie-out & auditability', description: 'Double-entry for platform/Stripe fees, payout journal, audit/export hooks', status: 'completed' },
            { id: 'ach-wallets', name: 'ACH & wallets', description: 'ACH, Apple/Google Pay, saved payment methods with mandates and retries', status: 'completed' },
            { id: 'chargebacks', name: 'Chargeback center', description: 'Dispute queue with evidence kits, webhook ingestion, and alerting', status: 'completed' },
        ],
    },
    {
        id: 'operations-automation',
        name: 'Operations Automation',
        description: 'SOPs, auto-tasking, inventory reorders, and copilot for staff workflows.',
        status: 'completed',
        order: 16,
        icon: 'bot',
        color: 'cyan',
        milestones: [
            { id: 'auto-tasking', name: 'Auto-tasking', description: 'Trigger maintenance/housekeeping tasks from events', status: 'completed' },
            { id: 'checklists', name: 'Checklists & SOPs', description: 'Reusable playbooks with due-times and owners', status: 'completed' },
            { id: 'inventory-reorders', name: 'Inventory reorders', description: 'Par levels with vendor reorders and approvals', status: 'completed' },
            { id: 'ops-copilot', name: 'Operations copilot', description: 'Suggested replies, task bundling, and smart routing', status: 'completed' },
        ],
    },
    {
        id: 'mobile-offline',
        name: 'Mobile & Offline',
        description: 'Field-ready staff tools, offline kiosk/pos, and resilient sync for low-connectivity parks.',
        status: 'completed',
        order: 17,
        icon: 'smartphone',
        color: 'emerald',
        milestones: [
            { id: 'pwa-lite', name: 'Guest & staff PWA slices', description: 'Lightweight PWA for arrivals/tasks and guest stay with messaging, orders-to-site requests, events, and offline queuing', status: 'completed' },
            { id: 'pwa-offline-hardening', name: 'Offline cache & queues', description: 'Service worker precache/runtime cache, indexedDB queues with retry/backoff, conflict handling, and sync telemetry', status: 'completed' },
            { id: 'offline-pos', name: 'Offline POS/kiosk', description: 'Take payments and issue passes offline with sync queue', status: 'completed' },
            { id: 'staff-mobile', name: 'Staff mobile', description: 'Work orders, arrivals, and messaging on mobile', status: 'completed' },
            { id: 'guest-mobile', name: 'Guest mobile', description: 'Guest stay app with offline map and orders', status: 'completed' },
            { id: 'push-notifs', name: 'Push notifications', description: 'Transactional and marketing pushes with preferences', status: 'completed' },
        ],
    },
    {
        id: 'integrations-ecosystem',
        name: 'Integrations & Ecosystem',
        description: 'Accounting, access control, CRM/helpdesk, and exports to meet operators where they are.',
        status: 'completed',
        order: 18,
        icon: 'plug',
        color: 'blue',
        milestones: [
            { id: 'accounting-sync', name: 'Accounting sync', description: 'QuickBooks/Xero mappings, reconciliation, and exports', status: 'completed' },
            { id: 'access-control', name: 'Access control', description: 'Smart lock/RFID integrations for gates and doors', status: 'completed' },
            { id: 'crm-helpdesk', name: 'CRM/helpdesk', description: 'Sync guests to HubSpot/Intercom/Zendesk with tickets', status: 'completed' },
            { id: 'data-exports', name: 'Data export APIs', description: 'Self-serve exports and SFTP drops for operators', status: 'completed' },
        ],
    },
    {
        id: 'personalization-ai',
        name: 'Personalization & AI Copilot',
        description: 'Richer data-driven recommendations, semantic search, and assistant-style workflows.',
        status: 'completed',
        order: 19,
        icon: 'sparkles',
        color: 'violet',
        milestones: [
            { id: 'recommendations', name: 'Recommendations', description: 'Site/upsell recommendations based on guest intent', status: 'completed' },
            { id: 'dynamic-pricing-ai', name: 'Dynamic pricing AI', description: 'Price suggestions using demand, comps, and rules', status: 'completed' },
            { id: 'semantic-search', name: 'Semantic search', description: 'Natural language search across guests, sites, and messages', status: 'completed' },
            { id: 'copilot', name: 'Copilot', description: 'Assistant for bulk changes, replies, and what-if planning', status: 'completed' },
        ],
    },
    {
        id: 'enterprise-international',
        name: 'Enterprise Scale & Internationalization',
        description: 'Multi-property ops, localization, tax/currency support, and approvals at scale.',
        status: 'completed',
        order: 20,
        icon: 'globe',
        color: 'amber',
        milestones: [
            { id: 'multi-property', name: 'Multi-property ops', description: 'Portfolio views, cross-park reporting, and routing', status: 'completed' },
            { id: 'localization', name: 'Localization', description: 'Multi-language UI and content with locale-aware formatting', status: 'completed' },
            { id: 'multi-currency', name: 'Multi-currency & tax', description: 'FX handling, VAT/GST, and regional tax rules', status: 'completed' },
            { id: 'approvals', name: 'Approvals & controls', description: 'Dual control for refunds, payouts, and high-value changes', status: 'completed' },
        ],
    },
    {
        id: 'support-helpdesk',
        name: 'Support & Helpdesk',
        description: 'Contextual help, inline guidance, and in-app support reporting with routed triage.',
        status: 'completed',
        order: 21,
        icon: 'life-buoy',
        color: 'slate',
        milestones: [
            { id: 'contextual-help', name: 'Contextual help panel', description: 'Slide-in help panel, /help hub, search, pinned/recent, role-aware filters, task pills, Shift+? shortcut', status: 'completed' },
            { id: 'inline-anchors', name: 'Inline help anchors', description: '“?” anchors across admin pages linking to relevant help topics', status: 'completed' },
            { id: 'support-reporting', name: 'In-app support reporting', description: 'Report form with auto-captured context, backend storage, admin queue', status: 'completed' },
            { id: 'support-routing', name: 'Support routing & alerts', description: 'Slack/email alerts, assignee picker, assignment notifications', status: 'completed' },
            { id: 'regional-scoping', name: 'Regional access & routing', description: 'Scope triage visibility/assignment by region/ownership roles', status: 'completed' },
            { id: 'staff-directory', name: 'Global staff directory', description: 'Cross-camp staff list for assignment and notifications', status: 'completed' },
        ],
    },
    {
        id: 'staff-gamification',
        name: 'Staff Gamification (Opt-in)',
        description: 'Mature, staff-only XP/levels tied to real work with challenges, badges, and dashboards. Opt-in per campground; guests never see it.',
        status: 'completed',
        order: 22,
        icon: 'target',
        color: 'purple',
        milestones: [
            { id: 'xp-system', name: 'XP system', description: 'XP for tasks, maintenance, check-ins, zero-error reservations, checklists, positive reviews, on-time assignments, and assists; light penalties for overdue/mistakes.', status: 'completed' },
            { id: 'levels', name: 'Levels & perks', description: 'Progression tiers with profile badges, early feature access, improvement-proposal queue, subtle themes.', status: 'completed' },
            { id: 'weekly-challenges', name: 'Weekly challenges', description: 'Auto-generated operational challenges with bonus XP and badges.', status: 'completed' },
            { id: 'leaderboards', name: 'Leaderboards', description: 'Category leaderboards (tasks, guest rating, check-in speed, cleanliness, consistency) with weekly/monthly resets.', status: 'completed' },
            { id: 'badges', name: 'Badges & achievements', description: 'Legit work-based badges (Rain or Shine, Fix It First, Guest Hero, Check-In Champion, Event Support Pro, Clean Sweep).', status: 'completed' },
            { id: 'performance-dashboard', name: 'Performance dashboard', description: 'Per-staff XP bar, level, badges, challenge status, leaderboard placement, task analytics, guest mentions, response times; manager team summaries.', status: 'completed' },
            { id: 'smart-notifs', name: 'Smart notifications', description: 'Encouraging nudges (e.g., “40 XP to Level 4—complete 3 tasks”, challenge countdowns, new badges).', status: 'completed' },
            { id: 'streaks-competitions', name: 'Streaks & team comps (optional)', description: 'Healthy streaks and friendly team competitions with XP/badge rewards.', status: 'completed' },
            { id: 'opt-in-controls', name: 'Opt-in & manager controls', description: 'Camp-level toggle; manager XP ranges, overrides, and manual Merit XP.', status: 'completed' },
            { id: 'anti-cheese', name: 'Anti-cheese design', description: 'Subtle, CRM/fitness-inspired visuals; no cartoon graphics or playful sounds.', status: 'completed' },
        ],
    },
    {
        id: 'stabilize',
        name: 'Stabilize & Hardening',
        description: 'POS/store resilience, guest/portal polish, trust/PII controls, OTA iCal sync, finance fixes.',
        status: 'completed',
        order: 23,
        icon: 'wrench',
        color: 'slate',
        milestones: [
            { id: 'pos-offline', name: 'POS offline queue & sync log', description: 'Queue orders, show sync state, charge-to-site hardening, refunds/credits, low-stock alerts', status: 'completed' },
            { id: 'guest-portal-polish', name: 'Guest portal polish', description: 'Comms timeline, delivery/curbside, assigned-on-arrival booking, order status, offline-friendly My Stay', status: 'completed' },
            { id: 'trust-privacy', name: 'Trust & compliance', description: 'Permissions guardrails, approval flows, audit/PII redaction, backups/restore-sim, retention', status: 'completed' },
            { id: 'ota-ical-next', name: 'OTA iCal sync', description: 'Per-listing calendar export/import with sync status and error badges', status: 'completed' },
            { id: 'finance-fixes', name: 'Finance fixes', description: 'Payouts/disputes views, deposits v2, ledger/tax sanity checks, finance seed fixtures', status: 'completed' },
        ],
    },
    {
        id: 'depth',
        name: 'Depth & Integrations',
        description: 'Two-way OTA, support/ops tooling, reporting/exports, integrations, and offline/PWA resilience.',
        status: 'completed',
        order: 24,
        icon: 'waves',
        color: 'indigo',
        milestones: [
            { id: 'ota-two-way', name: 'Two-way OTA', description: 'Availability/rates/reservations with logs, retry, per-channel status', status: 'completed' },
            { id: 'support-ops', name: 'Support & Ops', description: 'SLA/overdue, ticketing, staff chat, ops tasks with photos/routes/checklists', status: 'completed' },
            { id: 'reporting-exports', name: 'Reporting & exports', description: 'Pickup/pace, saved reports, CSV/S3 export, warehouse connector stub, scheduled exports', status: 'completed' },
            { id: 'integrations-wave1', name: 'Integrations wave 1', description: 'Accounting (payout/GL export), helpdesk/CRM, access control stubs, webhook retry/logs', status: 'completed' },
            { id: 'pwa-offline', name: 'PWA/offline', description: 'Queued orders/payments/messages, push notifications, visible sync state, conflict resolution', status: 'completed' },
        ],
    },
    {
        id: 'platform-scale',
        name: 'Platform & Scale',
        description: 'Public API/webhooks, SDKs, AI assist, IoT hooks, enterprise/international packs.',
        status: 'in_progress',
        order: 25,
        icon: 'globe-2',
        color: 'teal',
        milestones: [
            { id: 'public-api', name: 'Public API & webhooks', description: 'OAuth2 sandbox, SDKs, client generators, webhook retry/logs', status: 'planned' },
            { id: 'ai-assist', name: 'AI assist', description: 'Replies, task bundling, routing, smart search, anomaly alerts across bookings/payments/comms', status: 'in_progress' },
            { id: 'iot-hooks', name: 'IoT hooks', description: 'Metering/lock/alert stubs, QR-at-site flows, device registry', status: 'planned' },
            { id: 'enterprise-international-next', name: 'Enterprise & international depth', description: 'Multi-property controls, approvals depth, localization, FX/tax packs, data residency', status: 'planned' },
        ],
    },
    {
        id: 'charity-roundup',
        name: 'Round Up for Charity',
        description: 'Enable guests to round up their reservation total to donate to campground-selected charities, with full accounting integration and reporting.',
        status: 'planned',
        order: 26,
        icon: 'heart',
        color: 'rose',
        milestones: [
            { id: 'charity-models', name: 'Charity data models', description: 'Charity registry, campground charity selection, donation tracking, and payout management', status: 'planned' },
            { id: 'charity-admin', name: 'Charity admin UI', description: 'Platform charity management, campground charity settings, enable/disable round-up', status: 'planned' },
            { id: 'roundup-checkout', name: 'Round-up at checkout', description: 'Guest opt-in UI during booking with charity info and round-up amount display', status: 'planned' },
            { id: 'charity-accounting', name: 'Charity accounting', description: 'Separate GL code for donations, liability tracking, journal entries, and payout reconciliation', status: 'planned' },
            { id: 'charity-reporting', name: 'Charity reporting', description: 'Donation totals, opt-in rates, per-charity breakdown, payout history, and tax exports', status: 'planned' },
        ],
    },
];

// =============================================================================
// UPDATES / CHANGELOG
// =============================================================================

export const updates: Update[] = [
    {
        id: 'update-2025-12-17-ai-analytics-charity',
        title: 'AI Analytics Hub & Charity Round-Up planning',
        date: '2025-12-17',
        body: 'Launched comprehensive Analytics Hub with AI-powered insights including anomaly detection, NPS analysis, improvement suggestions, and goal tracking. Added NPS recognition badges (Top 1%, Rising Star, Campground of the Year). Started Platform & Scale phase with AI assist. Planning Round Up for Charity feature to let guests donate to campground-selected charities.',
        tags: ['analytics', 'ai', 'nps', 'charity', 'roadmap'],
        category: 'feature',
        phaseId: 'platform-scale',
        milestoneIds: ['ai-assist'],
    },
    {
        id: 'update-2025-12-16-ship-readiness-complete',
        title: 'Ship Readiness & Stabilize phases completed',
        date: '2025-12-16',
        body: 'Officially completed the Ship Readiness and Stabilize tracks. Validated build integrity, documented known limitations, performed full browser QA on production, and verified functional completion of Guest Portal, POS Offline, Trust/Compliance, and OTA iCal sync.',
        tags: ['roadmap', 'status', 'shipping', 'qa'],
        category: 'improvement',
        phaseId: 'ship-readiness',
        milestoneIds: ['pre-ship-qa-polish', 'ship-checklist'],
    },
    {
        id: 'update-2025-12-11-hardening-alerts-payments-pos',
        title: 'Reliability, payments, POS/stored value hardening shipped',
        date: '2025-12-11',
        body: 'Shipped alerting + synthetics with /ready split, idempotency store and rate limits, POS till open/close with needs-review on tender mismatch, stored value safeguards (taxable-load, liability snapshot), report export guard with resumable tokens, and consent/quiet-hour enforcement for email/SMS. Next: gateway choice + fee pass-through, big reports library, POS integrations, onboarding/import/export, e-sign/waivers/COI, utilities/late fees, access automation, referrals.',
        tags: ['reliability', 'payments', 'pos', 'alerts', 'exports', 'comms'],
        category: 'improvement',
        phaseId: 'ship-readiness',
        milestoneIds: [],
    },
    {
        id: 'update-2025-12-10-phase1-pricing-complete',
        title: 'Phase 1 (pricing, deposits, add-ons) completed',
        date: '2025-12-10',
        body: 'Wrapped Phase 1: dynamic pricing/seasonal plans, deposits/auto-collect rules, add-ons/upsells, automated comms hooks, and audit/RBAC hardening are shipped. Moving remaining work to later-phase polish.',
        tags: ['roadmap', 'pricing', 'deposits', 'upsells', 'status'],
        category: 'feature',
        phaseId: 'stabilize',
        milestoneIds: [],
    },
    {
        id: 'update-2025-12-10-phase3-ota-memberships-web-complete',
        title: 'Phase 3 (OTA, memberships, public website) completed',
        date: '2025-12-10',
        body: 'Finished the Phase 3 distribution & sales track: OTA/channel manager sync, memberships/discount plans & promo codes, and public website/SEO tools per park are now shipped. Follow-on polish will roll into future tracks.',
        tags: ['roadmap', 'ota', 'memberships', 'seo', 'status'],
        category: 'feature',
        phaseId: 'depth',
        milestoneIds: [],
    },
    {
        id: 'update-2025-12-10-phase2-complete',
        title: 'Phase 2 feature track marked complete',
        date: '2025-12-10',
        body: 'Phase 2 feature plan is now complete: shipped the scoped items and closed remaining tasks. Any further work will roll into next-phase tracks or polish.',
        tags: ['roadmap', 'status', 'completion'],
        category: 'improvement',
        phaseId: 'stabilize',
        milestoneIds: [],
    },
    {
        id: 'update-2025-12-09-roadmap-refresh',
        title: 'Roadmap refresh with phased planning snapshot',
        date: '2025-12-09',
        body: 'Updated the public/internal roadmaps and in-app Roadmap page with a phased plan: Phase 1 (dynamic pricing, deposits/auto-collect, add-ons/upsells, automated comms, audit/RBAC), Phase 2 (housekeeping/turnover tasking, maintenance tickets, self-service check-in, group/linked bookings), Phase 3 (OTA/channel sync, memberships/discounts, public website/SEO), Phase 4 (gift cards/store credit, POS, reporting/analytics, waitlist auto-offers). Public Now/Next/Later themes now match this plan.',
        tags: ['roadmap', 'planning', 'strategy'],
        category: 'improvement',
        phaseId: 'foundation',
        milestoneIds: [],
    },
    {
        id: 'update-2025-12-08-native-app-placeholder',
        title: 'Native app placeholder with PWA handoff',
        date: '2025-12-08',
        body: 'Packaged the guest/staff PWA slices into a lightweight native shell with store listing copy, kept push registration/preferences ready behind feature flags, and affirmed offline parity by reusing the existing service worker caches and queues.',
        tags: ['mobile', 'native', 'pwa', 'push', 'offline'],
        category: 'feature',
        phaseId: 'advanced',
        milestoneIds: ['mobile-app'],
    },
    {
        id: 'update-2025-12-08-guest-mobile-live',
        title: 'Guest PWA live with offline map, orders, and messaging',
        date: '2025-12-08',
        body: 'Guest-facing PWA is live: My Stay, orders-to-site, messaging, and a cached campground map all work offline with the existing service worker/queue. Guests can browse, place orders, and chat even on spotty Wi-Fi; changes sync once back online.',
        tags: ['guest', 'pwa', 'offline', 'orders', 'messaging'],
        category: 'feature',
        phaseId: 'mobile-offline',
        milestoneIds: ['guest-mobile'],
    },
    {
        id: 'update-2025-12-22-pre-ship-qa-plan',
        title: 'Pre-ship QA and UI polish plan staged',
        date: '2025-12-22',
        body: 'Captured a ship-blocker QA plan across dev/staging/prod: coverage matrix for public booking/portal/PWA, POS/kiosk, admin ops/finance/support/marketing/settings, and integrations; browser focus on Chromium with mobile/Firefox/Safari gaps noted. No new features—only QA, security/privacy checks, and UI/nav polish.',
        tags: ['qa', 'shipping', 'audit', 'ui'],
        category: 'improvement',
        phaseId: 'ship-readiness',
        milestoneIds: [],
    },
    {
        id: 'update-2025-12-22-pre-ship-qa-execution',
        title: 'QA execution track (in progress)',
        date: '2025-12-22',
        body: 'To-dos: run full E2E audit per environment; polish navigation/menu for professionalism; verify security/privacy/DR quick-audit and consent/PII exports; triage/fix only ship-blockers; re-smoke dev→staging→prod after fixes. No feature work unless required to ship.',
        tags: ['qa', 'shipping', 'security', 'ui'],
        category: 'improvement',
        phaseId: 'ship-readiness',
        milestoneIds: [],
    },
    {
        id: 'update-2025-12-08-support-analytics-pane',
        title: 'Support analytics snapshot for SLA compliance',
        date: '2025-12-08',
        body: 'Added an Admin → Support analytics pane with per-region/camp SLA compliance, category volume, and a needs-attention list. Data is stubbed and served from a lightweight API smoke to match the final metrics shape.',
        tags: ['support', 'analytics', 'sla'],
        category: 'feature',
        phaseId: 'support-helpdesk',
        milestoneIds: ['support-reporting'],
    },
    {
        id: 'update-2025-12-08-staff-mobile-shell',
        title: 'Lean staff-mobile shell with quick actions',
        date: '2025-12-08',
        body: 'Mobile-first housekeeping, maintenance, and messages layouts with a bottom quick-actions bar for tasks, messages, checklists, and ops health. Frontend-only and reuses existing data.',
        tags: ['staff', 'mobile', 'operations'],
        category: 'improvement',
        phaseId: 'mobile-offline',
        milestoneIds: ['staff-mobile'],
    },
    {
        id: 'update-2025-12-08-backup-dr-readiness',
        title: 'Backup/DR readiness card with stub restore drill',
        date: '2025-12-08',
        body: 'Settings → Security now surfaces last backup timestamp, retention window, and a stub “simulate restore” drill status with corresponding API/test coverage. Endpoints stay stub-only—no real restores are triggered.',
        tags: ['dr', 'backup', 'security'],
        category: 'infrastructure',
        phaseId: 'performance-reliability',
        milestoneIds: ['dr-readiness'],
    },
    {
        id: 'update-2025-12-08-ota-placeholder',
        title: 'OTA/channel placeholder with stub sync status',
        date: '2025-12-08',
        body: 'Added a minimal Settings → OTA card to capture provider IDs/keys plus a stubbed sync status panel. Backend exposes a stub OTA config endpoint with a smoke test, keeping everything in-app with no external calls.',
        tags: ['ota', 'sync', 'stub'],
        category: 'feature',
        phaseId: 'advanced',
        milestoneIds: ['ota'],
    },
    {
        id: 'update-2025-12-08-staff-mobile',
        title: 'Staff mobile quick actions for ops, maintenance, and messages',
        date: '2025-12-08',
        body: 'Polished staff-facing ops, maintenance, and messaging layouts for phones with responsive cards and a mobile quick actions bar to jump into tickets or chats. No backend or API changes required.',
        tags: ['staff', 'mobile', 'operations'],
        category: 'improvement',
        phaseId: 'mobile-offline',
        milestoneIds: ['staff-mobile'],
    },
    {
        id: 'update-2025-12-08-staff-mobile-support',
        title: 'Support joins staff mobile quick actions',
        date: '2025-12-08',
        body: 'Support triage now shares the same mobile quick-actions bar and padding as operations, maintenance, and messaging so staff have consistent jump points on phones.',
        tags: ['staff', 'mobile', 'support'],
        category: 'improvement',
        phaseId: 'mobile-offline',
        milestoneIds: ['staff-mobile'],
    },
    {
        id: 'update-2025-12-08-guest-upsells',
        title: 'Guest portal upsell cards with offline queueing',
        date: '2025-12-08',
        body: 'Added targeted upsell cards (late checkout, firewood delivery, activities) to My Stay. Cards scope to the guest’s campground and use stubbed availability; “Add to stay” queues locally via the existing offline queue so nothing calls external services.',
        tags: ['guest-portal', 'upsells', 'offline', 'queue'],
        category: 'feature',
        phaseId: 'guests',
        milestoneIds: ['portal-upsells'],
    },
    {
        id: 'update-2025-12-08-gift-cards',
        title: 'Gift cards & store credit stubbed',
        date: '2025-12-08',
        body: 'Added Finance → Gift Cards slice: issue codes with balance/expiry, redeem to reservations or POS orders, and view usage history with local-only storage (no external processors).',
        tags: ['finance', 'pos', 'gift-cards'],
        category: 'feature',
        phaseId: 'commerce',
        milestoneIds: ['gift-cards'],
    },
    {
        id: 'update-2025-12-08-pos-refunds',
        title: 'POS refunds/exchanges logged in history',
        date: '2025-12-08',
        body: 'Added a simple POS refund/exchange flow: pick a recent order, select items and amount, leave a note, and record it without touching a payment processor. Refunds/exchanges now surface in POS order history for quick reference.',
        tags: ['pos', 'refunds', 'commerce'],
        category: 'feature',
        phaseId: 'commerce',
        milestoneIds: ['pos-refunds'],
    },
    {
        id: 'update-2025-12-08-nps-scheduling',
        title: 'Flexible NPS scheduling + comms playbooks',
        date: '2025-12-08',
        body: 'Camp-level NPS now supports auto post-checkout sends plus configurable before/after arrival/departure schedules with template overrides, enable/disable toggles, and a send-hour. Admins manage schedules in Settings → Communications with a live preview. A smoke test seeds a schedule and asserts playbook jobs enqueue at the correct offsets.',
        tags: ['communications', 'nps', 'automation'],
        category: 'feature',
        phaseId: 'feedback-reputation',
        milestoneIds: ['auto-post-checkout-nps'],
    },
    {
        id: 'update-2025-12-08-equipment-rentals',
        title: 'Equipment rentals slice stubbed under Operations',
        date: '2025-12-08',
        body: 'Added an Equipment Rentals page with local-only data: create/edit rental items (name, type, rate, deposit) per campground, see a compact list + 7-day availability view, and run stubbed checkout/return actions to mark items assigned or returned. No external systems are called.',
        tags: ['operations', 'inventory', 'rentals'],
        category: 'feature',
        phaseId: 'activities',
        milestoneIds: ['equipment-rental'],
    },
    {
        id: 'update-2025-12-08-activities-depth',
        title: 'Activity caps, overage alerts, and waitlists',
        date: '2025-12-08',
        body: 'Admin Activities now shows capacity and remaining spots with overage alerts, lets staff adjust caps, and captures waitlist adds against a stubbed capacity endpoint—no external systems required.',
        tags: ['activities', 'capacity', 'waitlist'],
        category: 'feature',
        phaseId: 'activities',
        milestoneIds: ['activities-rentals-depth'],
    },
    {
        id: 'update-2025-12-08-referrals-affiliates',
        title: 'Referrals & affiliates links added with payout/export stubs',
        date: '2025-12-08',
        body: 'Added a referrals/affiliates slice under Marketing → Promotions: generate tracking links, view referral rows across pending/approved/paid, and run stubbed payout/export actions with no external money movement.',
        tags: ['marketing', 'referrals', 'affiliates'],
        category: 'feature',
        phaseId: 'growth-engine',
        milestoneIds: ['referrals'],
    },
    {
        id: 'update-2025-12-08-abandoned-cart',
        title: 'Abandoned cart recovery stubbed end-to-end',
        date: '2025-12-08',
        body: 'Public booking abandons now land in a stubbed recovery queue, surfaced in Ops with last activity/channel plus a “send recovery” action that routes through existing communications endpoints. Added a smoke test covering the queue/list APIs.',
        tags: ['marketing', 'recovery', 'communications'],
        category: 'feature',
        phaseId: 'growth-engine',
        milestoneIds: ['abandoned-cart'],
    },
    {
        id: 'update-2025-12-08-lead-capture-stub',
        title: 'Lead capture and CRM sync stubbed',
        date: '2025-12-08',
        body: 'Landing-page lead form (name, email, interest) scoped per campground plus Admin Marketing → Leads with new/contacted/qualified statuses and a stubbed “sync to CRM” button. All data stays in-app.',
        tags: ['marketing', 'leads', 'crm'],
        category: 'feature',
        phaseId: 'marketing',
        milestoneIds: ['lead-capture'],
    },
    {
        id: 'update-2025-12-08-social-planner',
        title: 'Social Media Planner minimal end-to-end slices shipped',
        date: '2025-12-08',
        body: 'Delivered the in-app Social Media Planner: calendar list/week views with parking-lot ideas, rule-based suggestions with refresh/accept/dismiss, weekly auto-generated bundles, a post builder with local tone/hashtag assists, template quick-use to parking lot, and reporting stubs. All flows stay in-app with no external posting.',
        tags: ['social', 'marketing', 'planner'],
        category: 'feature',
        phaseId: 'social-media-planner',
        milestoneIds: ['smp-calendar', 'smp-suggestions', 'smp-weekly-ideas', 'smp-post-builder', 'smp-templates', 'smp-content-bank', 'smp-reporting', 'smp-team', 'smp-strategy', 'smp-captions'],
    },
    {
        id: 'update-2025-12-08-promo-insights',
        title: 'Promo optimizer view stubbed under Marketing',
        date: '2025-12-08',
        body: 'Added a compact promo optimizer in Marketing → Promotions with A/B conversion + revenue/booking lift readouts and a “what to do next” stub, all using mock data.',
        tags: ['promotions', 'analytics', 'marketing'],
        category: 'improvement',
        phaseId: 'growth-engine',
        milestoneIds: ['promo-optimizer'],
    },
    {
        id: 'update-2025-12-08-staff-gamification',
        title: 'Staff Gamification (opt-in) slices delivered',
        date: '2025-12-08',
        body: 'Delivered opt-in staff gamification slices with XP, levels, weekly challenges, badges, leaderboards, and manager overrides. Included staff/admin UIs, manual merit XP, opt-in gates, and stubbed data to demo the full flow without external dependencies.',
        tags: ['staff', 'gamification', 'xp', 'leaderboard'],
        category: 'feature',
        phaseId: 'staff-gamification',
        milestoneIds: ['xp-system', 'levels', 'weekly-challenges', 'leaderboards', 'badges', 'performance-dashboard', 'smart-notifs', 'streaks-competitions', 'opt-in-controls', 'anti-cheese'],
    },
    {
        id: 'update-2025-12-08-data-intel-foundation',
        title: 'Data Intelligence foundation shipped: tracking, pricing insights, recs, reports',
        date: '2025-12-08',
        body: 'Delivered the foundational analytics slice: structured event tracking across booking flow, basic conversion/pricing insights, a recommendation stub with apply/propose, and an admin reports dashboard MVP. Everything runs in mock-friendly mode—no warehouse required.',
        tags: ['data', 'analytics', 'pricing', 'recommendations', 'reports'],
        category: 'feature',
        phaseId: 'data-intelligence',
        milestoneIds: ['event-tracking-layer', 'pricing-intelligence', 'recommendation-engine', 'reports-dashboard'],
    },
    {
        id: 'update-2025-12-12-support-regional-staff',
        title: 'Regional-scoped triage and staff directory',
        date: '2025-12-12',
        body: 'Support triage now scopes visibility and assignment by region and campground, blocking cross-region updates. The staff directory filters by region/campground, supports notify/assign actions for permitted staff only, and adds controls to set staff region and ownership roles.',
        tags: ['support', 'helpdesk', 'staff', 'regional'],
        category: 'feature',
        phaseId: 'support-helpdesk',
        milestoneIds: ['regional-scoping', 'staff-directory'],
    },
    {
        id: 'update-2025-12-08-enterprise-international',
        title: 'Enterprise scale: portfolios, localization, FX/tax, approvals',
        date: '2025-12-08',
        body: 'Delivered minimal end-to-end enterprise slices: portfolio listing/switcher with cross-park reporting and routing headers; localization settings with locale-aware formatting and previews; multi-currency + VAT/GST config with FX stub and per-park mapping; approvals dual control for refunds, payouts, and high-value config with policies and inbox UI.',
        tags: ['enterprise', 'portfolio', 'i18n', 'fx', 'tax', 'approvals'],
        category: 'feature',
        phaseId: 'enterprise-international',
        milestoneIds: ['multi-property', 'localization', 'multi-currency', 'approvals'],
    },
    {
        id: 'update-2025-12-08-personalization-ai',
        title: 'Personalization & AI Copilot: recs, pricing, search, copilot',
        date: '2025-12-08',
        body: 'Shipped stubbed AI flows end-to-end: recommendations by intent, dynamic pricing suggestions using demand/comps/rules, semantic search across guests/sites/messages, and copilot previews for bulk changes/replies/what-ifs. Backend APIs are wired with mock data (no external keys) and a minimal admin surface to exercise them. Added mock fallback mode for CampGuide endpoints (auto-returns stubs when AI is off/no key, with ?mock=true override).',
        tags: ['ai', 'recommendations', 'pricing', 'search', 'copilot'],
        category: 'feature',
        phaseId: 'personalization-ai',
        milestoneIds: ['recommendations', 'dynamic-pricing-ai', 'semantic-search', 'copilot'],
    },
    {
        id: 'update-2025-12-08-developer-ecosystem',
        title: 'Developer ecosystem: OAuth2 public API, webhooks, SDK, sandbox',
        date: '2025-12-08',
        body: 'Launched the developer surface: OAuth2 (client_credentials + refresh) with scoped per-campground tokens, guarded CRUD for reservations/guests/sites, and signed webhooks with HMAC headers, delivery logs, disable/replay, and admin controls. Added admin UI for credentials/webhooks, a TypeScript SDK with mock client, sandbox seeding plus sample API client/secret, and a dashboard embed hook for partner blocks.',
        tags: ['api', 'webhooks', 'oauth2', 'sdk', 'sandbox'],
        category: 'feature',
        phaseId: 'developer-ecosystem',
        milestoneIds: ['public-api', 'webhooks', 'sdk-sandbox', 'extensions'],
    },
    {
        id: 'update-2025-12-21-perf-reliability',
        title: 'Performance & Reliability: SLOs, rate limits, queues, DR runbook',
        date: '2025-12-21',
        body: 'Shipped lightweight observability with API SLOs (p95/99 + error rate), job telemetry, and a snapshot endpoint powering the tech dashboard. Added per-IP/org rate limits with 429s, queue/backpressure for campaign dispatch and payout reconciliation, and CI bundle-size budgets for the web app. Documented SLO targets, rollout steps, and a DR runbook with RPO/RTO, failover toggles, and game-day checks.',
        tags: ['observability', 'slo', 'rate-limits', 'queues', 'dr', 'budgets'],
        category: 'infrastructure',
        phaseId: 'performance-reliability',
        milestoneIds: ['observability', 'perf-budgets', 'rate-limits', 'dr-readiness'],
    },
    {
        id: 'update-2025-12-22-phase-completion',
        title: 'Advanced, Feedback/Reputation, and Growth Engine completed',
        date: '2025-12-22',
        body: 'Swept the roadmap to mark the Advanced Features, Feedback & Reputation, and Growth Engine tracks as fully completed now that every milestone is shipped. Roadmap views now show all three phases closed with their deliverables live.',
        tags: ['roadmap', 'advanced', 'feedback', 'growth'],
        category: 'feature',
        phaseId: 'growth-engine',
        milestoneIds: [],
    },
    {
        id: 'update-2025-12-08-integrations-ecosystem',
        title: 'Integrations wave 1 shipped: accounting, access control, CRM/helpdesk, exports (sandbox live)',
        date: '2025-12-08',
        body: 'Delivered plumbing + admin surfaces for Integrations & Ecosystem: camp-level connections for QuickBooks/Xero, access control, CRM/helpdesk, and exports with credential storage, status, last sync, manual sync/export triggers, and webhook ingestion with HMAC verification and log viewers. Added a minimal TS SDK for partner-side calls and sandbox QBO pull path; production QBO/Xero and some access-control/CRM credentials are pending partner approval.',
        tags: ['integrations', 'accounting', 'access-control', 'crm', 'exports', 'webhooks'],
        category: 'feature',
        phaseId: 'integrations-ecosystem',
        milestoneIds: ['accounting-sync', 'access-control', 'crm-helpdesk', 'data-exports'],
    },
    {
        id: 'update-2025-12-09-trust-compliance-complete',
        title: 'Trust, Compliance & Controls shipped: audit, permissions, privacy, runbook',
        date: '2025-12-09',
        body: 'Delivered the Trust, Compliance & Controls track end-to-end: immutable audit trails with CSV export, scoped approvals and field-level permission policies, and privacy/PII controls with redaction toggles, consent logging, and key/backup retention settings (stub/test storage). Added admin UI for audit viewer/export, permission policies/approvals, and privacy/consent controls, plus a brief backup/retention + approvals runbook. Stub creds only; wire to production secrets/infra before GA.',
        tags: ['trust', 'compliance', 'audit', 'privacy', 'permissions', 'consent'],
        category: 'infrastructure',
        phaseId: 'trust-compliance',
        milestoneIds: ['audit-trails', 'granular-permissions', 'privacy-controls', 'compliance'],
    },
    {
        id: 'update-2025-12-09-support-regions-directory',
        title: 'Support & Helpdesk: regional scoping and staff directory shipped',
        date: '2025-12-09',
        body: 'Scoped support triage to regions/ownership roles and enforced regional checks on listing and assignment. Added a global staff directory API and UI with region filter and stub notifications, plus region picker on the support queue. Existing support flows stay intact; data is stub-friendly.',
        tags: ['support', 'helpdesk', 'routing', 'regions', 'directory'],
        category: 'feature',
        phaseId: 'support-helpdesk',
        milestoneIds: ['regional-scoping', 'staff-directory'],
    },
    {
        id: 'update-2025-12-09-operations-automation-complete',
        title: 'Operations Automation: auto-tasking, checklists, reorders, copilot',
        date: '2025-12-09',
        body: 'Delivered Operations Automation end-to-end: stubbed auto-task triggers, SOP/checklist listings, inventory reorder suggestions, and ops copilot recommendations with admin UI cards. Backend surfaces new endpoints; frontend shows triggers, checklists, reorders, and apply buttons to validate the flow.',
        tags: ['operations', 'automation', 'checklists', 'reorders', 'copilot'],
        category: 'feature',
        phaseId: 'operations-automation',
        milestoneIds: ['auto-tasking', 'checklists', 'inventory-reorders', 'ops-copilot'],
    },
    {
        id: 'update-2025-12-10-data-intelligence-complete',
        title: 'Data Intelligence & Decision Engine shipped: tracking, insights, apply',
        date: '2025-12-10',
        body: 'Shipped the Data Intelligence & Decision Engine track with structured booking-flow event ingestion, image/site/pricing/deal conversion analytics, recommendations with Apply/Propose, and AI suggestion stubs. Admin analytics UI shows funnel, pricing signals, image/deal performance, attribution, and recommendations with apply/propose + annual CSV export. Backend endpoints remain stub-friendly; ready for real signals.',
        tags: ['data', 'analytics', 'recommendations', 'tracking', 'ai'],
        category: 'feature',
        phaseId: 'data-intelligence',
        milestoneIds: ['event-tracking-layer', 'image-conversion', 'site-conversion', 'pricing-intelligence', 'deal-analytics', 'recommendation-engine', 'reports-dashboard', 'ab-testing', 'permissions-privacy', 'annual-report', 'ml-future'],
    },
    {
        id: 'update-2025-12-08-performance-reliability-baseline',
        title: 'Performance & Reliability track activated with live perf snapshot',
        date: '2025-12-08',
        body: 'Turned on the Performance & Reliability track with end-to-end latency observability and guards: a lightweight perf interceptor now records per-route timings and 5xxs into a rolling in-memory window, exposed via /ops/perf. Added per-IP and per-org rate limits with counters surfaced alongside p50/p95/p99 and error rate. The web Tech page now shows the live perf snapshot to validate the path. Perf budgets remain staged for CI wiring next.',
        tags: ['performance', 'reliability', 'latency', 'observability', 'rate-limits'],
        category: 'infrastructure',
        phaseId: 'performance-reliability',
        milestoneIds: ['observability', 'perf-budgets', 'rate-limits'],
    },
    {
        id: 'update-2025-12-08-comms-quality-automation',
        title: 'Comms deliverability, templates/approvals, playbooks, and routing/SLAs shipped',
        date: '2025-12-08',
        body: 'Delivered end-to-end communications hardening: DMARC/DKIM/SPF verification with per-sender status, bounce/complaint classification, and Postmark/Twilio retries with provider failover/backoff plus health surfaces in timelines/inbox. Added per-campground template library with preview/smoke-send, versioning, approvals, and audit log. Automation playbooks now run arrivals, unpaid, upsell, and abandoned-cart sequences with quiet hours, routing rules, throttles, and a jobs monitor. Inbox/guest/reservation timelines show SLA timers/badges and ownership while keeping unread handling intact. Webhooks remain intact; manual verification done for deliverability checks, playbook firing, and SLA badges.',
        tags: ['communications', 'deliverability', 'templates', 'playbooks', 'routing', 'sla', 'webhooks'],
        category: 'feature',
        phaseId: 'communications-automation',
        milestoneIds: ['provider-health', 'templating', 'automation-playbooks', 'inbox-routing'],
    },
    {
        id: 'update-2025-12-08-mobile-offline-complete',
        title: 'Mobile & Offline: service worker, queues, POS/kiosk, push',
        date: '2025-12-08',
        body: 'Completed the Mobile & Offline track: service worker now precaches PWA/portal shells and runtime-caches key APIs with versioned busting; all write flows use IndexedDB-backed queues with idempotency keys, exponential backoff, background sync, conflict detection (ETag/updatedAt), and retry/resolve UI. POS and kiosk support offline carts/check-ins with duplicate guard and replay; portal store/activities and guest messages queue offline with conflict handling. Added sync telemetry/logs, queue badges with conflicts/last error, and a sync log page with manual flush and conflict resolution. Push preferences now capture permissions and device registrations with local fallback when server push endpoint isn’t configured. SW update flow broadcasts activation and prompts users to refresh.',
        tags: ['pwa', 'offline', 'pos', 'kiosk', 'push', 'sync'],
        category: 'feature',
        phaseId: 'mobile-offline',
        milestoneIds: ['pwa-offline-hardening', 'offline-pos', 'push-notifs'],
    },
    {
        id: 'update-2025-12-08-activate-gap-work',
        title: 'In-progress: comms deliverability, payouts/ACH/disputes, offline POS',
        date: '2025-12-08',
        body: 'Moved key gaps into active work streams: communications deliverability (DMARC/DKIM/SPF checks, provider failover, template approvals, automation playbooks, inbox routing/SLAs), payments & fintech (payout reconciliation, ledger tie-out for platform/Stripe fees, ACH/wallets, chargeback center), and mobile/offline (offline POS/kiosk, push notifications, service worker + queues already underway).',
        tags: ['roadmap', 'in-progress', 'communications', 'payments', 'offline'],
        category: 'infrastructure',
        phaseId: 'foundation',
        milestoneIds: [],
    },
    {
        id: 'update-2025-12-15-data-intelligence-roadmap',
        title: 'Data Intelligence & Decision Engine roadmap defined',
        date: '2025-12-15',
        body: 'Added privacy-first analytics and Decision Engine track: structured booking-flow events, image/site/pricing/deal conversion analytics, recommendation hub with confidence/impact and permissions-gated Apply/Update buttons, reports dashboard tabs, A/B testing, annual data report, and ML-ready hooks for forecasting/alerts.',
        tags: ['data', 'analytics', 'recommendations', 'privacy', 'ab-testing', 'reports'],
        category: 'feature',
        phaseId: 'data-intelligence',
        milestoneIds: ['event-tracking-layer', 'image-conversion', 'site-conversion', 'pricing-intelligence', 'deal-analytics', 'recommendation-engine', 'reports-dashboard', 'ab-testing', 'annual-report', 'ml-future'],
    },
    {
        id: 'update-2025-12-06-mobile-offline-audit',
        title: 'Mobile/offline audit and hardening plan',
        date: '2025-12-06',
        body: 'Ran the staff arrivals/tasks and guest My Stay PWA slices in low-connectivity mode. Findings: no registered service worker or precache/runtime caching; guest messages queue to localStorage only (no background sync/backoff), staff view and arrivals/tasks fall back to blank when offline, and POS/kiosk are online-only. Push notifications are not wired. OTA iCal feeds/imports and sync logs work online but have no offline story. Next up: service worker with versioned precache + runtime caching, indexedDB-backed queues for messages/orders/payments with retry/backoff, conflict detection on reservation/tasks/inventory updates, and surfaced sync logs/telemetry.',
        tags: ['pwa', 'offline', 'mobile', 'sync', 'ota', 'pos'],
        category: 'improvement',
        phaseId: 'mobile-offline',
        milestoneIds: ['pwa-lite', 'pwa-offline-hardening', 'offline-pos', 'push-notifs'],
    },
    {
        id: 'update-2025-12-06-communications-automation-audit',
        title: 'Comms automation audit: status badges and gaps',
        date: '2025-12-06',
        body: 'Verified Postmark/Twilio webhooks capture provider message IDs and update delivery status badges across guest/reservation timelines and the inbox. Outbound email prefers Postmark with SMTP fallback. Missing pieces remain: DMARC/DKIM/SPF enforcement, bounce classification, retries/failover, template approvals, and automation playbooks for arrivals/unpaid/upsells/abandoned carts.',
        tags: ['communications', 'deliverability', 'automation', 'webhooks'],
        category: 'infrastructure',
        phaseId: 'communications-automation',
        milestoneIds: ['provider-health', 'templating', 'automation-playbooks', 'inbox-routing'],
    },
    {
        id: 'update-2025-12-14-feedback-reputation',
        title: 'NPS + Reviews: automation, dashboard, public filters',
        date: '2025-12-14',
        body: 'Shipped NPS core (surveys, invites, responses, detractor tickets/alerts, promoter → review requests), admin feedback dashboard (metrics, survey creation, manual invites, moderation with remove), reports overview NPS cards, and public reviews with filters (rating, tags, photos-only), search, relevance/newest/photo-first sorting, rating distribution bars, photo badges, lazy “show more”. Behind the scenes: auto post-checkout NPS send at 7am day-after is wired in code but needs campground settings re-added (npsAutoSendEnabled/npsSendHour) before enabling.',
        tags: ['nps', 'reviews', 'reputation', 'ux', 'automation'],
        category: 'feature',
        phaseId: 'feedback-reputation',
        milestoneIds: ['nps-core', 'feedback-dashboard', 'public-reviews', 'auto-post-checkout-nps'],
    },
    {
        id: 'update-2025-12-06-payments-fintech-validation',
        title: 'Stripe Connect validated; payout/ACH/dispute gaps flagged',
        date: '2025-12-06',
        body: 'Validated per-booking fees and plans using Stripe Connect with application fees and pass-through toggle in staff/public flows. Gaps identified: no payout reconciliation/export job, no ledger lines for platform/Stripe fees or double-entry tie-out, no saved wallets/ACH or setup intents, and no chargeback/dispute UI, evidence kits, or alerting. Next: add payout + fee journal + recon job + admin payout report, enable ACH/wallet payment methods with mandates and retries, and build a dispute center with evidence templates and alerts.',
        tags: ['payments', 'stripe', 'connect', 'ledger', 'ach', 'chargebacks'],
        category: 'infrastructure',
        phaseId: 'payments-fintech',
        milestoneIds: ['platform-fees', 'payout-recon', 'ledger-audit', 'ach-wallets', 'chargebacks'],
    },
    {
        id: 'update-2025-12-20-payments-fintech-complete',
        title: 'Payout recon, ledger audit, ACH/wallets, and chargeback center',
        date: '2025-12-20',
        body: 'Completed Payments & Fintech: hourly payout reconciliation with drift alerts, payout detail + CSV/ledger exports, and double-entry for platform/Stripe fees and chargebacks. ACH and wallets (Apple/Google Pay) are exposed via setup intents and booking UI messaging; ACH returns post chargeback offsets. Chargeback center adds dispute list, evidence templates, CSV export, SLA banners, and due-by alerts. Drift/ACH/dispute alerts route via webhook env when set.',
        tags: ['payments', 'stripe', 'ach', 'wallets', 'chargebacks', 'ledger', 'reconciliation'],
        category: 'feature',
        phaseId: 'payments-fintech',
        milestoneIds: ['payout-recon', 'ledger-audit', 'ach-wallets', 'chargebacks'],
    },
    {
        id: 'update-2025-12-20-payments-fintech-done',
        title: 'Payout recon, ledger audit, ACH/wallets, and chargeback center shipped',
        date: '2025-12-20',
        body: 'Delivered end-to-end payouts recon with balance transaction ingestion, drift alerts, CSV and ledger exports, and admin UI for payout detail. Double-entry ledger covers platform/Stripe fees and chargebacks. ACH and wallet setup intents are exposed for staff/public with ACH return handling. Chargeback center now has dispute list/detail, evidence templates, SLA banners, exports, and webhook-driven ingestion. Telemetry alerts fire for payout drift and disputes due soon.',
        tags: ['payments', 'stripe', 'payouts', 'ach', 'wallets', 'chargebacks', 'ledger', 'alerts'],
        category: 'feature',
        phaseId: 'payments-fintech',
        milestoneIds: ['payout-recon', 'ledger-audit', 'ach-wallets', 'chargebacks'],
    },
    {
        id: 'update-2025-12-13-pwa-ota-audit',
        title: 'PWA guest/staff offline slices, OTA iCal, and audit hardening',
        date: '2025-12-13',
        body: 'Shipped lightweight PWA views: staff arrivals/tasks and guest “My Stay” with messaging, order-to-site requests, events, and offline queuing; added manifest/icons and offline fallback. OTA iCal export/import with mapping logs is live; availability push stubs update sync stats. Reports got sub-tabs, saved reports (per user), pickup rollups/CSV, and UI polish. Staff invites, role guards, and audit logs (IP/UA, CSV diff) are in place. Menu now accordion-folds. Next: provider APIs for OTA, PWA store/pay offline with service worker.',
        tags: ['pwa', 'offline', 'ota', 'reports', 'audit', 'staff', 'guest'],
        category: 'feature',
        phaseId: 'mobile-offline',
        milestoneIds: ['pwa-lite', 'ota-ical', 'ota', 'reports', 'communication-hub'],
    },
    {
        id: 'update-2025-12-06-campaigns-ux-prisma',
        title: 'Campaigns UX refresh and schema hardening',
        date: '2025-12-06',
        body: 'Admin campaigns page now uses a two-column layout with a dedicated audience preview card and auto-run previews when suggestions are applied. Suggested audiences stay in view alongside templates, reducing scroll. Behind the scenes: campaign/suggestion APIs were stabilized by fixing Prisma relations (campaign sends, OTA mappings) to keep data loading; next agent just needs to run pnpm install/prisma generate and restart the API to align the client.',
        tags: ['campaigns', 'marketing', 'ux', 'prisma', 'backend'],
        category: 'improvement',
        phaseId: 'marketing',
        milestoneIds: ['email-campaigns'],
    },
    {
        id: 'update-2025-12-12-support-routing',
        title: 'Support reporting, triage, and routed alerts',
        date: '2025-12-12',
        body: 'Staff can file in-app issues with auto-captured context (URL, browser, timezone, viewport, role filter, pinned/recent, campground). Backend stores reports with owner-guarded GET/PATCH; admin console lists, filters, and lets staff update status and assign via campground members. Slack/webhook and email alerts fire on create; assignee gets notified on assignment.',
        tags: ['support', 'alerts', 'routing', 'admin'],
        category: 'feature',
        phaseId: 'support-helpdesk',
        milestoneIds: ['support-reporting', 'support-routing'],
    },
    {
        id: 'update-2025-12-12-contextual-help',
        title: 'Contextual help panel, /help hub, and inline “?” anchors',
        date: '2025-12-12',
        body: 'Help panel (Shift+?) now shows contextual topics, search with boosted scoring/typo tolerance, pinned/recent, role filters, task pills, copy-link, and feedback. Full /help mirrors filters and pins. Inline “?” anchors were added across key admin pages to deep-link into the right topics.',
        tags: ['help', 'docs', 'ux'],
        category: 'feature',
        phaseId: 'support-helpdesk',
        milestoneIds: ['contextual-help', 'inline-anchors'],
    },
    {
        id: 'update-2025-12-06-ota-ical',
        title: 'OTA iCal feeds, imports, and mapping logs',
        date: '2025-12-06',
        body: 'OTA channels now support per-listing iCal feeds (export) and inbound iCal imports to block availability. Channels show mapping status, last sync/error, and sync logs; webhooks are HMAC-protected and create reservations with ledger lines and site-class fallback. Availability push is stubbed for now but logs per listing. UI adds push availability, imports, and logs tabs.',
        tags: ['ota', 'ical', 'availability', 'imports', 'logging'],
        category: 'feature',
        phaseId: 'advanced',
        milestoneIds: ['ota-ical', 'ota'],
    },
    {
        id: 'update-2025-12-06-branding-policies-forms',
        title: 'Branding, cancellation policies, and forms templates',
        date: '2025-12-06',
        body: 'Structured branding fields (logo/colors/font/email header/receipt footer), cancellation policy fields (type/window/fee/notes), and new forms/templates with submissions tied to reservations or guests. Form submissions block check-in until completed; reservation/guest pages now show form statuses.',
        tags: ['branding', 'policies', 'forms', 'compliance', 'check-in'],
        category: 'feature',
        phaseId: 'trust-compliance',
        milestoneIds: [],
    },
    {
        id: 'update-2025-12-06-promo-analytics-forms-ui',
        title: 'Promo analytics and forms UX surfaced',
        date: '2025-12-06',
        body: 'Marketing reports now show live promo codes, usage, and redemptions filtered by the page date range, plus active-only filtering. Forms UI supports creating/editing templates and attaching them to reservations/guests; pending counts surface on reservation and guest detail pages.',
        tags: ['promotions', 'reports', 'forms', 'ux'],
        category: 'improvement',
        phaseId: 'marketing',
        milestoneIds: ['promotions', 'reports'],
    },
    {
        id: 'update-2025-12-06-pickup-reporting',
        title: 'Pickup reporting with rollups and CSV',
        date: '2025-12-06',
        body: 'Forecasting and revenue tabs now include pickup reporting: 7/30/90-day deltas, weekly and monthly rollups, occupancy%, and CSV export with all windows. Filters support interval, comparison windows, site class, reservation status, and activity-only rows.',
        tags: ['reports', 'pickup', 'csv', 'revenue', 'forecasting'],
        category: 'feature',
        phaseId: 'marketing',
        milestoneIds: ['reports', 'pickup-reporting'],
    },
    {
        id: 'update-2025-12-05-comms-badges',
        title: 'Comms timelines with delivery/status badges',
        date: '2025-12-05',
        body: 'Reservation and guest communications timelines now surface direction, provider, to/from, and delivery status badges (sent/received/delivered/failed). Messages view mirrors the badges for consistency, keeping unread handling intact.',
        tags: ['communications', 'email', 'sms', 'ux'],
        category: 'improvement',
        phaseId: 'guests',
        milestoneIds: ['communication-hub', 'guest-messaging'],
    },
    {
        id: 'update-2025-12-11-onsite-ordering',
        title: 'On-site ordering live in guest portal',
        date: '2025-12-11',
        body: 'Guests can now order camp store items and add-ons from the portal, pay by card, or charge to their reservation. Cart/checkout ties to the current stay, with availability and rig-fit safeguards already in place.',
        tags: ['guest-portal', 'ordering', 'store', 'pos'],
        category: 'feature',
        phaseId: 'guests',
        milestoneIds: ['onsite-ordering'],
    },
    {
        id: 'update-2025-12-10-payments-live',
        title: 'Per-campground payments live with platform fees',
        date: '2025-12-10',
        body: 'Stripe Connect is live: each campground can onboard its own account, and the platform can charge per-booking fees or monthly plans, with absorb vs pass-through options. Public and admin flows now create intents against the connected account with application fees.',
        tags: ['payments', 'stripe', 'fees', 'connect'],
        category: 'feature',
        phaseId: 'foundation',
        milestoneIds: ['payment-integration'],
    },
    {
        id: 'update-2025-12-10-rig-fit',
        title: 'Rig-fit matching shipped',
        date: '2025-12-10',
        body: 'Rig-fit is live: availability and booking now filter by RV length and type using site and site-class limits. Overlength rigs see sites locked, and admin/public booking only show compatible options. Next: surface mismatch reasons in UI.',
        tags: ['availability', 'rig-fit', 'search', 'booking'],
        category: 'feature',
        phaseId: 'availability',
        milestoneIds: ['rig-fit'],
    },
    {
        id: 'update-2025-12-09-communications-postmark',
        title: 'Unified guest communications + Postmark outbound',
        date: '2025-12-09',
        body: 'All guest communications (email, SMS, internal notes) now log to both guest and reservation timelines. Outbound email switched to Postmark to capture provider message IDs, with Twilio/Postmark webhooks updating delivery status. Admin messaging gets unread badges and per-conversation tracking so staff see new guest or DM messages instantly.',
        tags: ['communications', 'email', 'sms', 'postmark', 'twilio', 'notifications'],
        category: 'feature',
        phaseId: 'guests',
        milestoneIds: ['communication-hub', 'guest-messaging'],
    },
    {
        id: 'update-2025-12-08-next-focus',
        title: 'Next up: payments, rig-fit, on-site ordering',
        date: '2025-12-08',
        body: 'With Reservations marked complete, we are focusing on Payment Integration, Rig-fit Matching, and On-site Ordering. Up next after that: SEO + Email Campaigns and the OTA + Mobile App tracks.',
        tags: ['roadmap', 'planning', 'seo', 'email', 'ota', 'mobile'],
        category: 'infrastructure',
        phaseId: 'foundation',
        milestoneIds: [],
    },
    {
        id: 'update-2025-12-07-nav-favorites',
        title: 'Admin navigation with Favorites & Most Visited',
        date: '2025-12-07',
        body: 'Streamlined the admin sidebar with collapsible sections plus personal Favorites and Most Visited links. Pins are edit-only for a cleaner look, keeping POS and Core Ops highly visible.',
        tags: ['ux', 'navigation', 'dashboard'],
        category: 'improvement',
        phaseId: 'foundation',
        milestoneIds: ['dashboard-shell'],
    },
    {
        id: 'update-2025-12-06-blackouts-holds',
        title: 'Blackouts, Holds, and Waitlist Automation',
        date: '2025-12-06',
        body: 'Added blackout date enforcement across availability, booking, and admin UI. Introduced site holds with auto-expiry and tied them into the public booking flow. Waitlist matching now auto-notifies guests when holds expire or dates free up, and ledger export is available for finance.',
        tags: ['blackouts', 'holds', 'waitlist', 'booking', 'operations'],
        category: 'feature',
        phaseId: 'availability',
        milestoneIds: ['blackout-dates', 'hold-system', 'waitlist'],
    },
    {
        id: 'update-2025-12-05-round-8',
        title: 'Activities, Memberships & Operations',
        date: '2025-12-05',
        body: 'Launched comprehensive Activities system for scheduling and booking events. Introduced Memberships for guest loyalty and discounts. Rolled out Operations dashboard for real-time housekeeping and maintenance task management.',
        tags: ['activities', 'memberships', 'operations', 'feature'],
        category: 'feature',
        phaseId: 'activities',
        milestoneIds: ['activity-mgmt', 'session-scheduling', 'guest-booking', 'maintenance'],
    },
    {
        id: 'update-2025-12-04-round-4',
        title: 'Advanced Features & Commerce Complete',
        date: '2025-12-04',
        body: 'Completed Round 4 including Maintenance System (blocking tickets), Events Calendar (public & admin), Inventory Management (stock tracking), and Email Notifications (transactional emails).',
        tags: ['maintenance', 'events', 'inventory', 'email', 'feature'],
        category: 'feature',
        phaseId: 'advanced',
        milestoneIds: ['maintenance', 'events', 'inventory-mgmt', 'communication-hub'],
    },
    {
        id: 'update-2025-12-04-store-backend',
        title: 'Store & Add-ons backend',
        date: '2025-12-04',
        body: 'Added database schema and API endpoints for product catalog, add-on services, and orders. Charge-to-site creates ledger entries and updates reservation balance automatically. Stock tracking with low-stock alerts.',
        tags: ['store', 'api', 'commerce', 'backend'],
        category: 'feature',
        phaseId: 'commerce',
        milestoneIds: ['product-catalog', 'addon-services', 'charge-to-site', 'inventory-mgmt'],
    },
    {
        id: 'update-2025-01-03-roadmap',
        title: 'Roadmap refresh',
        date: '2025-01-03',
        body: 'Reprioritized phases: focus first on financial backbone, site classes/pricing, reservation payments/status, campground branding/season, guest depth, and availability/rig-fit. Moved the fully live "living interactive map" to a later phase after core ops and accounting are solid.',
        tags: ['planning', 'roadmap'],
        category: 'infrastructure',
        phaseId: 'foundation',
        milestoneIds: [],
    },
    {
        id: 'update-2025-01-02-pos',
        title: 'POS UI added',
        date: '2025-01-02',
        body: 'Initial POS UI mockup with products catalog, shopping cart, and checkout flow. Store inventory and add-ons system planned for upcoming development.',
        tags: ['pos', 'frontend', 'commerce'],
        category: 'feature',
        phaseId: 'commerce',
        milestoneIds: ['staff-pos'],
    },
    {
        id: 'update-2025-01-02-forms',
        title: 'Forms & shell',
        date: '2025-01-02',
        body: 'Campground/site/reservation create/delete forms, dropdown selectors, breadcrumb navigation, and soft enterprise styling throughout. Dashboard shell is now complete.',
        tags: ['forms', 'ui', 'dashboard'],
        category: 'feature',
        phaseId: 'foundation',
        milestoneIds: ['dashboard-shell'],
    },
    {
        id: 'update-2025-01-01-scaffold',
        title: 'Platform scaffold',
        date: '2025-01-01',
        body: 'NestJS + Prisma API, Next.js 15 frontend, shared Zod types across packages, basic CRUD for organizations, campgrounds, sites, guests, and reservations. Dashboard shell with sidebar navigation is live.',
        tags: ['api', 'frontend', 'infrastructure'],
        category: 'infrastructure',
        phaseId: 'foundation',
        milestoneIds: ['platform-scaffold', 'multi-org', 'dashboard-shell'],
    },
];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

export function getPhaseById(id: string): RoadmapPhase | undefined {
    return roadmapPhases.find(p => p.id === id);
}

export function getMilestoneById(phaseId: string, milestoneId: string): Milestone | undefined {
    const phase = getPhaseById(phaseId);
    return phase?.milestones.find(m => m.id === milestoneId);
}

export function getUpdatesForPhase(phaseId: string): Update[] {
    return updates.filter(u => u.phaseId === phaseId);
}

export function getPhaseProgress(phase: RoadmapPhase): { completed: number; total: number; percentage: number } {
    const completed = phase.milestones.filter(m => m.status === 'completed').length;
    const total = phase.milestones.length;
    return { completed, total, percentage: total === 0 ? 0 : Math.round((completed / total) * 100) };
}

export function getAllTags(): string[] {
    const tagSet = new Set<string>();
    updates.forEach(u => u.tags.forEach(t => tagSet.add(t)));
    return Array.from(tagSet).sort();
}

export const categoryColors: Record<UpdateCategory, { bg: string; text: string; border: string }> = {
    feature: { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
    improvement: { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
    bugfix: { bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200' },
    infrastructure: { bg: 'bg-violet-50', text: 'text-violet-700', border: 'border-violet-200' },
};

export const statusColors: Record<PhaseStatus, { bg: string; text: string }> = {
    completed: { bg: 'bg-emerald-100', text: 'text-emerald-800' },
    in_progress: { bg: 'bg-blue-100', text: 'text-blue-800' },
    planned: { bg: 'bg-slate-100', text: 'text-slate-600' },
};

export const statusLabels: Record<PhaseStatus, string> = {
    completed: 'Completed',
    in_progress: 'In Progress',
    planned: 'Planned',
};
