/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-prisma-enums.js
 *
 * This file provides TypeScript enum declarations for Prisma 7 enums.
 * Prisma 7 exports enums as const objects, but our codebase expects
 * TypeScript enums. This module augmentation provides the expected types.
 *
 * Regenerate after schema changes:
 *   node scripts/generate-prisma-enums.js
 */

declare module "@prisma/client" {
  export enum ReservationStatus {
    pending = "pending",
    confirmed = "confirmed",
    checked_in = "checked_in",
    checked_out = "checked_out",
    cancelled = "cancelled",
  }

  export enum SiteType {
    rv = "rv",
    tent = "tent",
    cabin = "cabin",
    group = "group",
    glamping = "glamping",
    hotel_room = "hotel_room",
    suite = "suite",
    lodge_room = "lodge_room",
    yurt = "yurt",
    treehouse = "treehouse",
    tiny_house = "tiny_house",
    airstream = "airstream",
    safari_tent = "safari_tent",
    dome = "dome",
    boat_slip = "boat_slip",
  }

  export enum MaintenanceStatus {
    open = "open",
    in_progress = "in_progress",
    closed = "closed",
  }

  export enum MaintenancePriority {
    low = "low",
    medium = "medium",
    high = "high",
    critical = "critical",
  }

  export enum CampaignStatus {
    draft = "draft",
    scheduled = "scheduled",
    sending = "sending",
    sent = "sent",
    cancelled = "cancelled",
  }

  export enum CampaignSendStatus {
    queued = "queued",
    sent = "sent",
    failed = "failed",
    unsubscribed = "unsubscribed",
  }

  export enum SupportReportStatus {
    new = "new",
    triage = "triage",
    in_progress = "in_progress",
    resolved = "resolved",
    closed = "closed",
  }

  export enum ChannelType {
    email = "email",
    sms = "sms",
    both = "both",
  }

  export enum UserRole {
    owner = "owner",
    manager = "manager",
    front_desk = "front_desk",
    maintenance = "maintenance",
    finance = "finance",
    marketing = "marketing",
    readonly = "readonly",
  }

  export enum SenderType {
    guest = "guest",
    staff = "staff",
  }

  export enum TaxRuleType {
    percentage = "percentage",
    flat = "flat",
    exemption = "exemption",
  }

  export enum RateType {
    nightly = "nightly",
    weekly = "weekly",
    monthly = "monthly",
    seasonal = "seasonal",
  }

  export enum StayType {
    standard = "standard",
    weekly = "weekly",
    monthly = "monthly",
    seasonal = "seasonal",
  }

  export enum StayReasonPreset {
    vacation = "vacation",
    family_visit = "family_visit",
    event = "event",
    work_remote = "work_remote",
    stopover = "stopover",
    relocation = "relocation",
    other = "other",
  }

  export enum ReferralIncentiveType {
    percent_discount = "percent_discount",
    amount_discount = "amount_discount",
    credit = "credit",
  }

  export enum PaymentSchedule {
    single = "single",
    weekly = "weekly",
    monthly = "monthly",
    as_you_stay = "as_you_stay",
    offseason_installments = "offseason_installments",
  }

  export enum PricingStructure {
    per_night = "per_night",
    flat_week = "flat_week",
    flat_month = "flat_month",
    flat_season = "flat_season",
  }

  export enum ChargeStatus {
    pending = "pending",
    paid = "paid",
    failed = "failed",
  }

  export enum TaskType {
    turnover = "turnover",
    inspection = "inspection",
    other = "other",
    deep_clean = "deep_clean",
    touch_up = "touch_up",
    make_ready = "make_ready",
    checkout_express = "checkout_express",
    vip_prep = "vip_prep",
    pet_treatment = "pet_treatment",
    linen_change = "linen_change",
    restocking = "restocking",
  }

  export enum HousekeepingStatus {
    vacant_dirty = "vacant_dirty",
    cleaning_in_progress = "cleaning_in_progress",
    pending_inspection = "pending_inspection",
    inspection_failed = "inspection_failed",
    vacant_clean = "vacant_clean",
    vacant_inspected = "vacant_inspected",
    occupied = "occupied",
    occupied_service = "occupied_service",
    occupied_dnd = "occupied_dnd",
    out_of_order = "out_of_order",
    out_of_inventory = "out_of_inventory",
  }

  export enum TaskState {
    pending = "pending",
    in_progress = "in_progress",
    blocked = "blocked",
    done = "done",
    failed = "failed",
    expired = "expired",
  }

  export enum SlaStatus {
    on_track = "on_track",
    at_risk = "at_risk",
    breached = "breached",
  }

  export enum TicketState {
    open = "open",
    in_progress = "in_progress",
    blocked = "blocked",
    resolved = "resolved",
    reopened = "reopened",
    closed = "closed",
  }

  export enum TicketCategory {
    issue = "issue",
    question = "question",
    feature = "feature",
    other = "other",
  }

  export enum Severity {
    low = "low",
    med = "med",
    high = "high",
    critical = "critical",
  }

  export enum CheckInStatus {
    not_started = "not_started",
    pending_id = "pending_id",
    pending_payment = "pending_payment",
    pending_waiver = "pending_waiver",
    pending_site_ready = "pending_site_ready",
    completed = "completed",
    failed = "failed",
  }

  export enum CheckOutStatus {
    not_started = "not_started",
    pending_review = "pending_review",
    completed = "completed",
    failed = "failed",
  }

  export enum IncidentStatus {
    open = "open",
    investigating = "investigating",
    resolved = "resolved",
    closed = "closed",
  }

  export enum IncidentType {
    injury = "injury",
    property_damage = "property_damage",
    safety = "safety",
    security = "security",
    near_miss = "near_miss",
    environmental = "environmental",
    other = "other",
  }

  export enum IncidentTaskStatus {
    pending = "pending",
    in_progress = "in_progress",
    done = "done",
    cancelled = "cancelled",
  }

  export enum EvidenceType {
    photo = "photo",
    document = "document",
    note = "note",
    audio = "audio",
    video = "video",
    other = "other",
  }

  export enum GroupRole {
    primary = "primary",
    member = "member",
  }

  export enum SocialPlatform {
    facebook = "facebook",
    instagram = "instagram",
    tiktok = "tiktok",
    email = "email",
    blog = "blog",
  }

  export enum SocialPostStatus {
    draft = "draft",
    scheduled = "scheduled",
    needs_image = "needs_image",
    needs_approval = "needs_approval",
    ready = "ready",
    completed = "completed",
    dismissed = "dismissed",
  }

  export enum SocialContentCategory {
    amenities = "amenities",
    events = "events",
    offers = "offers",
    reviews = "reviews",
    tips = "tips",
    general = "general",
    promo = "promo",
  }

  export enum SocialTemplateStyle {
    short = "short",
    detailed = "detailed",
    story = "story",
    carousel = "carousel",
    announce = "announce",
  }

  export enum SocialAssetType {
    photo = "photo",
    video = "video",
    logo = "logo",
    template = "template",
    other = "other",
  }

  export enum SocialSuggestionType {
    idea = "idea",
    auto = "auto",
    operator = "operator",
    occupancy = "occupancy",
    event = "event",
    deal = "deal",
    seasonal = "seasonal",
  }

  export enum SocialSuggestionStatus {
    new = "new",
    accepted = "accepted",
    rejected = "rejected",
    published = "published",
  }

  export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
  }

  export enum PermissionEffect {
    allow = "allow",
    deny = "deny",
  }

  export enum PlatformRole {
    support_agent = "support_agent",
    support_lead = "support_lead",
    regional_support = "regional_support",
    ops_engineer = "ops_engineer",
    platform_admin = "platform_admin",
  }

  export enum PiiClassification {
    basic = "basic",
    sensitive = "sensitive",
    payment = "payment",
    secret = "secret",
  }

  export enum RedactionMode {
    mask = "mask",
    remove = "remove",
  }

  export enum ConsentMethod {
    verbal = "verbal",
    written = "written",
    digital = "digital",
  }

  export enum SocialAlertCategory {
    weather = "weather",
    occupancy = "occupancy",
    events = "events",
    deals = "deals",
    reviews = "reviews",
    inactivity = "inactivity",
    inventory = "inventory",
  }

  export enum OnboardingStatus {
    pending = "pending",
    in_progress = "in_progress",
    completed = "completed",
    expired = "expired",
    cancelled = "cancelled",
  }

  export enum OnboardingStep {
    park_profile = "park_profile",
    operational_hours = "operational_hours",
    stripe_connect = "stripe_connect",
    inventory_choice = "inventory_choice",
    data_import = "data_import",
    site_classes = "site_classes",
    sites_builder = "sites_builder",
    rate_periods = "rate_periods",
    rates_setup = "rates_setup",
    fees_and_addons = "fees_and_addons",
    tax_rules = "tax_rules",
    booking_rules = "booking_rules",
    deposit_policy = "deposit_policy",
    cancellation_rules = "cancellation_rules",
    waivers_documents = "waivers_documents",
    park_rules = "park_rules",
    team_setup = "team_setup",
    communication_setup = "communication_setup",
    integrations = "integrations",
    menu_setup = "menu_setup",
    feature_discovery = "feature_discovery",
    smart_quiz = "smart_quiz",
    feature_triage = "feature_triage",
    guided_setup = "guided_setup",
    review_launch = "review_launch",
    account_profile = "account_profile",
    payment_gateway = "payment_gateway",
    taxes_and_fees = "taxes_and_fees",
    inventory_sites = "inventory_sites",
    rates_and_fees = "rates_and_fees",
    policies = "policies",
    communications_templates = "communications_templates",
    pos_hardware = "pos_hardware",
    imports = "imports",
  }

  export enum CampgroundClaimStatus {
    unclaimed = "unclaimed",
    claim_pending = "claim_pending",
    claimed = "claimed",
  }

  export enum ClaimVerificationMethod {
    phone = "phone",
    email = "email",
    document = "document",
    domain = "domain",
    manual = "manual",
  }

  export enum CampgroundDataSource {
    recreation_gov = "recreation_gov",
    reserve_california = "reserve_california",
    reserve_america = "reserve_america",
    nps = "nps",
    usfs = "usfs",
    blm = "blm",
    state_parks = "state_parks",
    osm = "osm",
    manual = "manual",
    user_submitted = "user_submitted",
    claimed = "claimed",
  }

  export enum SeoLocationType {
    country = "country",
    state = "state",
    region = "region",
    county = "county",
    city = "city",
    neighborhood = "neighborhood",
    attraction = "attraction",
  }

  export enum AttractionType {
    national_park = "national_park",
    state_park = "state_park",
    national_forest = "national_forest",
    national_monument = "national_monument",
    lake = "lake",
    beach = "beach",
    river = "river",
    mountain = "mountain",
    ski_resort = "ski_resort",
    theme_park = "theme_park",
    historic_site = "historic_site",
    scenic_byway = "scenic_byway",
    wildlife_area = "wildlife_area",
    recreation_area = "recreation_area",
    other = "other",
  }

  export enum SubscriptionTier {
    free = "free",
    starter = "starter",
    professional = "professional",
    enterprise = "enterprise",
  }

  export enum BillingPlan {
    ota_only = "ota_only",
    standard = "standard",
    enterprise = "enterprise",
  }

  export enum EarlyAccessTier {
    founders_circle = "founders_circle",
    pioneer = "pioneer",
    trailblazer = "trailblazer",
  }

  export enum PaymentFeeMode {
    absorb = "absorb",
    pass_through = "pass_through",
  }

  export enum PaymentGatewayProvider {
    stripe = "stripe",
    adyen = "adyen",
    authorize_net = "authorize_net",
    other = "other",
  }

  export enum PaymentGatewayMode {
    test = "test",
    prod = "prod",
  }

  export enum NpsSurveyStatus {
    draft = "draft",
    active = "active",
    paused = "paused",
    archived = "archived",
  }

  export enum NpsInviteStatus {
    queued = "queued",
    sent = "sent",
    bounced = "bounced",
    opened = "opened",
    responded = "responded",
    expired = "expired",
  }

  export enum ReviewStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    removed = "removed",
  }

  export enum ReviewSource {
    onsite = "onsite",
    email = "email",
    sms = "sms",
    kiosk = "kiosk",
    import = "import",
  }

  export enum ReviewExposure {
    private = "private",
    public = "public",
  }

  export enum ReviewVoteValue {
    helpful = "helpful",
    not_helpful = "not_helpful",
  }

  export enum ReviewModerationStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
  }

  export enum AnalyticsEventName {
    page_view = "page_view",
    site_card_view = "site_card_view",
    image_viewed = "image_viewed",
    image_hovered = "image_hovered",
    image_clicked = "image_clicked",
    site_class_viewed = "site_class_viewed",
    availability_check = "availability_check",
    add_to_stay = "add_to_stay",
    reservation_start = "reservation_start",
    reservation_abandoned = "reservation_abandoned",
    reservation_completed = "reservation_completed",
    deal_viewed = "deal_viewed",
    deal_applied = "deal_applied",
    email_signup = "email_signup",
    review_viewed = "review_viewed",
    admin_page_view = "admin_page_view",
    admin_action = "admin_action",
    admin_search = "admin_search",
    admin_error = "admin_error",
    admin_feature_use = "admin_feature_use",
    admin_session_start = "admin_session_start",
    admin_session_end = "admin_session_end",
    admin_pricing_change = "admin_pricing_change",
    admin_image_reorder = "admin_image_reorder",
    funnel_step = "funnel_step",
    funnel_abandon = "funnel_abandon",
    funnel_complete = "funnel_complete",
    portal_login = "portal_login",
    portal_view = "portal_view",
    portal_action = "portal_action",
  }

  export enum AbTestStatus {
    draft = "draft",
    active = "active",
    paused = "paused",
    stopped = "stopped",
    completed = "completed",
  }

  export enum GamificationEventCategory {
    task = "task",
    maintenance = "maintenance",
    check_in = "check_in",
    reservation_quality = "reservation_quality",
    checklist = "checklist",
    review_mention = "review_mention",
    on_time_assignment = "on_time_assignment",
    assist = "assist",
    manual = "manual",
    other = "other",
    payment_collection = "payment_collection",
  }

  export enum FormAutoAttachMode {
    manual = "manual",
    all_bookings = "all_bookings",
    site_classes = "site_classes",
  }

  export enum FormShowAt {
    during_booking = "during_booking",
    at_checkin = "at_checkin",
    after_booking = "after_booking",
    on_demand = "on_demand",
  }

  export enum FormTemplateType {
    waiver = "waiver",
    vehicle = "vehicle",
    intake = "intake",
    custom = "custom",
  }

  export enum FormSubmissionStatus {
    pending = "pending",
    completed = "completed",
    void = "void",
  }

  export enum AccessProviderType {
    kisi = "kisi",
    brivo = "brivo",
    cloudkey = "cloudkey",
  }

  export enum AccessGrantStatus {
    pending = "pending",
    active = "active",
    revoked = "revoked",
    blocked = "blocked",
    expired = "expired",
    failed = "failed",
  }

  export enum AccessCredentialType {
    pin = "pin",
    card = "card",
    fob = "fob",
    mobile = "mobile",
    qr = "qr",
  }

  export enum GlPeriodStatus {
    open = "open",
    closed = "closed",
    locked = "locked",
  }

  export enum GlAccountType {
    asset = "asset",
    liability = "liability",
    equity = "equity",
    revenue = "revenue",
    expense = "expense",
  }

  export enum PayoutStatus {
    pending = "pending",
    in_transit = "in_transit",
    paid = "paid",
    failed = "failed",
    canceled = "canceled",
  }

  export enum PayoutReconStatus {
    pending = "pending",
    matched = "matched",
    drift = "drift",
    failed = "failed",
  }

  export enum DisputeStatus {
    warning_needs_response = "warning_needs_response",
    warning_under_review = "warning_under_review",
    needs_response = "needs_response",
    under_review = "under_review",
    charge_refunded = "charge_refunded",
    won = "won",
    lost = "lost",
  }

  export enum EventType {
    activity = "activity",
    workshop = "workshop",
    entertainment = "entertainment",
    holiday = "holiday",
    recurring = "recurring",
    ongoing = "ongoing",
    themed = "themed",
  }

  export enum AddOnPricingType {
    flat = "flat",
    per_night = "per_night",
    per_person = "per_person",
  }

  export enum OrderStatus {
    pending = "pending",
    ready = "ready",
    delivered = "delivered",
    completed = "completed",
    cancelled = "cancelled",
    refunded = "refunded",
  }

  export enum PaymentMethod {
    card = "card",
    cash = "cash",
    charge_to_site = "charge_to_site",
  }

  export enum OrderChannel {
    pos = "pos",
    online = "online",
    kiosk = "kiosk",
    portal = "portal",
    internal = "internal",
  }

  export enum FulfillmentType {
    pickup = "pickup",
    curbside = "curbside",
    delivery = "delivery",
    table_service = "table_service",
  }

  export enum ChannelInventoryMode {
    shared = "shared",
    split = "split",
  }

  export enum ProductInventoryMode {
    shared = "shared",
    per_location = "per_location",
  }

  export enum StoreLocationType {
    physical = "physical",
    virtual = "virtual",
  }

  export enum InventoryTransferStatus {
    pending = "pending",
    in_transit = "in_transit",
    completed = "completed",
    cancelled = "cancelled",
  }

  export enum FulfillmentAssignmentStatus {
    unassigned = "unassigned",
    assigned = "assigned",
    preparing = "preparing",
    ready = "ready",
    completed = "completed",
  }

  export enum ExpirationTier {
    fresh = "fresh",
    warning = "warning",
    critical = "critical",
    expired = "expired",
  }

  export enum MarkdownDiscountType {
    percentage = "percentage",
    flat = "flat",
  }

  export enum MarkdownScope {
    all = "all",
    category = "category",
    product = "product",
  }

  export enum BatchDisposalReason {
    expired = "expired",
    damaged = "damaged",
    quality_issue = "quality_issue",
    recall = "recall",
    theft_loss = "theft_loss",
    donation = "donation",
    sample = "sample",
    other = "other",
  }

  export enum StoreAdjustmentType {
    refund = "refund",
    exchange = "exchange",
    discount = "discount",
  }

  export enum PromotionType {
    percentage = "percentage",
    flat = "flat",
  }

  export enum WaitlistStatus {
    active = "active",
    fulfilled = "fulfilled",
    expired = "expired",
    cancelled = "cancelled",
  }

  export enum WaitlistType {
    regular = "regular",
    seasonal = "seasonal",
  }

  export enum WaitlistOfferStatus {
    pending = "pending",
    sent = "sent",
    accepted = "accepted",
    declined = "declined",
    expired = "expired",
    failed = "failed",
  }

  export enum FeatureSetupStatus {
    setup_now = "setup_now",
    setup_later = "setup_later",
    skipped = "skipped",
    completed = "completed",
  }

  export enum ActivitySchedulingMode {
    scheduled = "scheduled",
    open_availability = "open_availability",
  }

  export enum RecurrencePatternType {
    none = "none",
    daily = "daily",
    weekly = "weekly",
    biweekly = "biweekly",
    monthly = "monthly",
  }

  export enum ApiClientTier {
    free = "free",
    standard = "standard",
    enterprise = "enterprise",
  }

  export enum PricingRuleType {
    season = "season",
    weekend = "weekend",
    holiday = "holiday",
    event = "event",
    demand = "demand",
  }

  export enum PricingStackMode {
    additive = "additive",
    max = "max",
    override = "override",
  }

  export enum AdjustmentType {
    percent = "percent",
    flat = "flat",
  }

  export enum DepositStrategy {
    first_night = "first_night",
    percent = "percent",
    fixed = "fixed",
  }

  export enum DepositApplyTo {
    lodging_only = "lodging_only",
    lodging_plus_fees = "lodging_plus_fees",
  }

  export enum DepositDueTiming {
    at_booking = "at_booking",
    before_arrival = "before_arrival",
  }

  export enum BackoffStrategy {
    fixed = "fixed",
    linear = "linear",
    exponential = "exponential",
  }

  export enum UpsellPriceType {
    flat = "flat",
    per_night = "per_night",
    per_guest = "per_guest",
    per_site = "per_site",
  }

  export enum UpsellChargeType {
    pay_now = "pay_now",
    add_to_reservation = "add_to_reservation",
  }

  export enum UpsellStatus {
    pending_charge = "pending_charge",
    charged = "charged",
    canceled = "canceled",
  }

  export enum IdempotencyStatus {
    pending = "pending",
    inflight = "inflight",
    succeeded = "succeeded",
    failed = "failed",
  }

  export enum DynamicPricingTrigger {
    occupancy_high = "occupancy_high",
    occupancy_low = "occupancy_low",
    demand_surge = "demand_surge",
    last_minute = "last_minute",
    advance_booking = "advance_booking",
    event_proximity = "event_proximity",
    weather = "weather",
    manual = "manual",
  }

  export enum WorkflowTrigger {
    reservation_created = "reservation_created",
    reservation_confirmed = "reservation_confirmed",
    days_before_arrival = "days_before_arrival",
    check_in = "check_in",
    days_after_checkin = "days_after_checkin",
    check_out = "check_out",
    days_after_checkout = "days_after_checkout",
    payment_received = "payment_received",
    payment_failed = "payment_failed",
    review_received = "review_received",
    birthday = "birthday",
    anniversary = "anniversary",
    manual = "manual",
  }

  export enum WorkflowStatus {
    active = "active",
    paused = "paused",
    draft = "draft",
    archived = "archived",
  }

  export enum WorkflowExecutionStatus {
    pending = "pending",
    running = "running",
    completed = "completed",
    failed = "failed",
    cancelled = "cancelled",
  }

  export enum WaiverStatus {
    pending = "pending",
    signed = "signed",
    expired = "expired",
    declined = "declined",
  }

  export enum SignatureDocumentType {
    long_term_stay = "long_term_stay",
    seasonal = "seasonal",
    monthly = "monthly",
    park_rules = "park_rules",
    deposit = "deposit",
    waiver = "waiver",
    coi = "coi",
    other = "other",
  }

  export enum SignatureRequestStatus {
    preview = "preview",
    draft = "draft",
    sent = "sent",
    viewed = "viewed",
    signed = "signed",
    signed_paper = "signed_paper",
    waived = "waived",
    declined = "declined",
    voided = "voided",
    expired = "expired",
  }

  export enum SignatureDeliveryChannel {
    email = "email",
    sms = "sms",
    email_and_sms = "email_and_sms",
  }

  export enum SignatureMethod {
    digital = "digital",
    paper = "paper",
    waived = "waived",
  }

  export enum WaiverReason {
    returning_same_terms = "returning_same_terms",
    corporate_agreement = "corporate_agreement",
    grandfathered = "grandfathered",
    family_member = "family_member",
    owner_discretion = "owner_discretion",
    other = "other",
  }

  export enum CoiStatus {
    pending = "pending",
    active = "active",
    expired = "expired",
    voided = "voided",
  }

  export enum IdVerificationStatus {
    pending = "pending",
    verified = "verified",
    failed = "failed",
    expired = "expired",
  }

  export enum ShiftStatus {
    scheduled = "scheduled",
    in_progress = "in_progress",
    submitted = "submitted",
    approved = "approved",
    rejected = "rejected",
  }

  export enum ShiftApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
  }

  export enum TimeEntryStatus {
    open = "open",
    submitted = "submitted",
    approved = "approved",
    rejected = "rejected",
    corrected = "corrected",
  }

  export enum TimeEntrySource {
    kiosk = "kiosk",
    mobile = "mobile",
    web = "web",
    manual = "manual",
  }

  export enum OverrideType {
    comp = "comp",
    void = "void",
    discount = "discount",
  }

  export enum OverrideStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    cancelled = "cancelled",
  }

  export enum TimeOffType {
    vacation = "vacation",
    sick = "sick",
    personal = "personal",
    bereavement = "bereavement",
    jury_duty = "jury_duty",
    unpaid = "unpaid",
    other = "other",
  }

  export enum TimeOffStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    cancelled = "cancelled",
  }

  export enum BreakType {
    paid = "paid",
    unpaid = "unpaid",
    meal = "meal",
    rest = "rest",
  }

  export enum SwapStatus {
    pending_recipient = "pending_recipient",
    pending_manager = "pending_manager",
    approved = "approved",
    rejected = "rejected",
    declined = "declined",
    cancelled = "cancelled",
  }

  export enum PayrollProvider {
    generic = "generic",
    onpay = "onpay",
    gusto = "gusto",
    adp = "adp",
  }

  export enum PayrollExportStatus {
    pending = "pending",
    generated = "generated",
    failed = "failed",
  }

  export enum PayrollExportFormat {
    csv = "csv",
    json = "json",
  }

  export enum PushNotificationType {
    arrival = "arrival",
    departure = "departure",
    task_assigned = "task_assigned",
    task_sla_warning = "task_sla_warning",
    maintenance_urgent = "maintenance_urgent",
    payment_received = "payment_received",
    payment_failed = "payment_failed",
    message_received = "message_received",
    general = "general",
  }

  export enum ReportScheduleFrequency {
    daily = "daily",
    weekly = "weekly",
    monthly = "monthly",
    quarterly = "quarterly",
  }

  export enum StoredValueType {
    gift = "gift",
    credit = "credit",
  }

  export enum StoredValueScopeType {
    campground = "campground",
    organization = "organization",
    global = "global",
  }

  export enum StoredValueStatus {
    active = "active",
    frozen = "frozen",
    expired = "expired",
  }

  export enum StoredValueDirection {
    issue = "issue",
    redeem = "redeem",
    adjust = "adjust",
    expire = "expire",
    refund = "refund",
    hold_create = "hold_create",
    hold_capture = "hold_capture",
    hold_release = "hold_release",
  }

  export enum StoredValueHoldStatus {
    open = "open",
    captured = "captured",
    released = "released",
    expired = "expired",
  }

  export enum PosCartStatus {
    open = "open",
    checked_out = "checked_out",
    void = "void",
  }

  export enum PosPaymentMethod {
    card = "card",
    cash = "cash",
    gift = "gift",
    store_credit = "store_credit",
    charge_to_site = "charge_to_site",
  }

  export enum PosPaymentStatus {
    pending = "pending",
    succeeded = "succeeded",
    failed = "failed",
    refunded = "refunded",
  }

  export enum TillSessionStatus {
    open = "open",
    closed = "closed",
  }

  export enum TillMovementType {
    cash_sale = "cash_sale",
    cash_refund = "cash_refund",
    paid_in = "paid_in",
    paid_out = "paid_out",
    adjustment = "adjustment",
  }

  export enum PosProviderType {
    clover = "clover",
    square = "square",
    toast = "toast",
    lightspeed = "lightspeed",
    shopify = "shopify",
    vend = "vend",
  }

  export enum PosProviderCapability {
    payments = "payments",
    items_sync = "items_sync",
    receipts = "receipts",
    inventory_push = "inventory_push",
    inventory_pull = "inventory_pull",
    markdown_sync = "markdown_sync",
    expiration_sync = "expiration_sync",
  }

  export enum PosIntegrationStatus {
    enabled = "enabled",
    disabled = "disabled",
    error = "error",
  }

  export enum PosSyncTarget {
    catalog = "catalog",
    tenders = "tenders",
    payments = "payments",
    inventory = "inventory",
    markdowns = "markdowns",
  }

  export enum PosSyncStatus {
    idle = "idle",
    running = "running",
    succeeded = "succeeded",
    failed = "failed",
  }

  export enum PosReturnStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed",
  }

  export enum AuditAction {
    CREATE = "CREATE",
    UPDATE = "UPDATE",
    DELETE = "DELETE",
    LOGIN = "LOGIN",
    LOGOUT = "LOGOUT",
    SYNC = "SYNC",
    EXPORT = "EXPORT",
    IMPORT = "IMPORT",
  }

  export enum FeatureFlagScope {
    global = "global",
    campground = "campground",
  }

  export enum AnnouncementType {
    info = "info",
    warning = "warning",
    success = "success",
  }

  export enum AnnouncementTarget {
    all = "all",
    admins = "admins",
    campground = "campground",
  }

  export enum AnnouncementStatus {
    draft = "draft",
    scheduled = "scheduled",
    sent = "sent",
  }

  export enum ReportFrequency {
    daily = "daily",
    weekly = "weekly",
    monthly = "monthly",
  }

  export enum ReportType {
    occupancy_summary = "occupancy_summary",
    revenue_summary = "revenue_summary",
    arrivals_departures = "arrivals_departures",
    maintenance_summary = "maintenance_summary",
    reservation_activity = "reservation_activity",
    guest_activity = "guest_activity",
    financial_summary = "financial_summary",
  }

  export enum AiFeatureType {
    reply_assist = "reply_assist",
    booking_assist = "booking_assist",
    analytics = "analytics",
    forecasting = "forecasting",
    anomaly_detection = "anomaly_detection",
    recommendations = "recommendations",
  }

  export enum AiConsentType {
    booking_assist = "booking_assist",
    personalization = "personalization",
    communications = "communications",
    analytics = "analytics",
  }

  export enum SegmentScope {
    global = "global",
    organization = "organization",
    campground = "campground",
  }

  export enum SegmentStatus {
    active = "active",
    archived = "archived",
  }

  export enum AnalyticsType {
    overview = "overview",
    geographic = "geographic",
    demographics = "demographics",
    seasonal_trends = "seasonal_trends",
    travel_behavior = "travel_behavior",
    full_report = "full_report",
    segment = "segment",
  }

  export enum ExportFormat {
    csv = "csv",
    json = "json",
    pdf = "pdf",
  }

  export enum ExportStatus {
    pending = "pending",
    processing = "processing",
    completed = "completed",
    failed = "failed",
  }

  export enum ShareAccessLevel {
    view_only = "view_only",
    downloadable = "downloadable",
  }

  export enum GoalStatus {
    on_track = "on_track",
    at_risk = "at_risk",
    behind = "behind",
    achieved = "achieved",
  }

  export enum GoalCategory {
    revenue = "revenue",
    bookings = "bookings",
    guests = "guests",
    satisfaction = "satisfaction",
  }

  export enum GoalUnit {
    currency = "currency",
    percentage = "percentage",
    number = "number",
    score = "score",
  }

  export enum AwardType {
    campground_of_year = "campground_of_year",
    rising_star = "rising_star",
    world_class = "world_class",
    top_1_percent = "top_1_percent",
    top_5_percent = "top_5_percent",
    top_10_percent = "top_10_percent",
  }

  export enum DonationStatus {
    collected = "collected",
    pending_payout = "pending_payout",
    paid_out = "paid_out",
    refunded = "refunded",
  }

  export enum CharityPayoutStatus {
    pending = "pending",
    processing = "processing",
    completed = "completed",
    failed = "failed",
  }

  export enum OrgBillingPeriodStatus {
    open = "open",
    processing = "processing",
    invoiced = "invoiced",
    paid = "paid",
    past_due = "past_due",
    void = "void",
  }

  export enum OrgBillingLineItemType {
    subscription = "subscription",
    booking_fee = "booking_fee",
    sms_outbound = "sms_outbound",
    sms_inbound = "sms_inbound",
    ai_usage = "ai_usage",
    overage = "overage",
    credit = "credit",
    discount = "discount",
    early_access_discount = "early_access_discount",
  }

  export enum SetupServiceType {
    quick_start = "quick_start",
    data_import_500 = "data_import_500",
    data_import_2000 = "data_import_2000",
    data_import_5000 = "data_import_5000",
    data_import_custom = "data_import_custom",
  }

  export enum SetupServiceStatus {
    pending = "pending",
    in_progress = "in_progress",
    completed = "completed",
    cancelled = "cancelled",
  }

  export enum OrgReferralStatus {
    clicked = "clicked",
    signed_up = "signed_up",
    converted = "converted",
    credited = "credited",
  }

  export enum GuaranteeType {
    unconditional = "unconditional",
    conditional = "conditional",
    performance = "performance",
    satisfaction = "satisfaction",
    weather = "weather",
    best_price = "best_price",
  }

  export enum OpTaskCategory {
    turnover = "turnover",
    housekeeping = "housekeeping",
    maintenance = "maintenance",
    inspection = "inspection",
    grounds = "grounds",
    pool = "pool",
    front_desk = "front_desk",
    custom = "custom",
  }

  export enum OpTaskState {
    pending = "pending",
    assigned = "assigned",
    in_progress = "in_progress",
    blocked = "blocked",
    completed = "completed",
    verified = "verified",
    cancelled = "cancelled",
  }

  export enum OpTaskPriority {
    low = "low",
    medium = "medium",
    high = "high",
    urgent = "urgent",
  }

  export enum OpSlaStatus {
    on_track = "on_track",
    at_risk = "at_risk",
    breached = "breached",
  }

  export enum OpTriggerEvent {
    reservation_checkout = "reservation_checkout",
    reservation_checkin = "reservation_checkin",
    reservation_created = "reservation_created",
    reservation_cancelled = "reservation_cancelled",
    reservation_modified = "reservation_modified",
    maintenance_reported = "maintenance_reported",
    inspection_failed = "inspection_failed",
    site_status_changed = "site_status_changed",
    manual = "manual",
  }

  export enum OpRecurrencePattern {
    daily = "daily",
    weekly = "weekly",
    biweekly = "biweekly",
    monthly = "monthly",
    seasonal = "seasonal",
  }

  export enum OpBadgeCategory {
    speed = "speed",
    volume = "volume",
    quality = "quality",
    streak = "streak",
    teamwork = "teamwork",
    milestone = "milestone",
    special = "special",
  }

  export enum OpBadgeTier {
    bronze = "bronze",
    silver = "silver",
    gold = "gold",
    platinum = "platinum",
  }

  export enum SeasonalBillingFrequency {
    monthly = "monthly",
    biweekly = "biweekly",
    semi_monthly = "semi_monthly",
    quarterly = "quarterly",
    semi_annual = "semi_annual",
    seasonal = "seasonal",
    deposit_plus_monthly = "deposit_plus_monthly",
    offseason_installments = "offseason_installments",
    custom = "custom",
  }

  export enum SeasonalStatus {
    active = "active",
    pending_renewal = "pending_renewal",
    not_renewing = "not_renewing",
    departed = "departed",
    waitlist = "waitlist",
  }

  export enum RenewalIntent {
    committed = "committed",
    likely = "likely",
    undecided = "undecided",
    not_renewing = "not_renewing",
  }

  export enum SeasonalDiscountCondition {
    metered_utilities = "metered_utilities",
    pay_in_full = "pay_in_full",
    payment_method = "payment_method",
    early_bird = "early_bird",
    returning_guest = "returning_guest",
    tenure_years = "tenure_years",
    site_class = "site_class",
    referral = "referral",
    military = "military",
    senior = "senior",
    custom = "custom",
  }

  export enum SeasonalDiscountType {
    fixed_amount = "fixed_amount",
    percentage = "percentage",
    per_month = "per_month",
  }

  export enum SeasonalIncentiveType {
    guest_passes = "guest_passes",
    store_credit = "store_credit",
    free_nights = "free_nights",
    early_site_selection = "early_site_selection",
    rate_lock = "rate_lock",
    amenity_access = "amenity_access",
    custom = "custom",
  }

  export enum SeasonalPaymentStatus {
    scheduled = "scheduled",
    due = "due",
    past_due = "past_due",
    paid = "paid",
    partial = "partial",
    waived = "waived",
  }

  export enum SeasonalPaymentMethod {
    check = "check",
    cash = "cash",
    card = "card",
    ach = "ach",
    autopay = "autopay",
  }

  export enum LockCodeType {
    gate = "gate",
    cabin = "cabin",
    amenity = "amenity",
    wifi = "wifi",
    master = "master",
  }

  export enum LockCodeRotationSchedule {
    none = "none",
    daily = "daily",
    weekly = "weekly",
    monthly = "monthly",
    per_guest = "per_guest",
  }

  export enum RateParityAlertStatus {
    active = "active",
    acknowledged = "acknowledged",
    resolved = "resolved",
  }

  export enum IssueStatus {
    backlog = "backlog",
    todo = "todo",
    in_progress = "in_progress",
    review = "review",
    done = "done",
  }

  export enum IssuePriority {
    low = "low",
    medium = "medium",
    high = "high",
    critical = "critical",
  }

  export enum IssueCategory {
    database = "database",
    frontend = "frontend",
    performance = "performance",
    security = "security",
    api = "api",
    infrastructure = "infrastructure",
    documentation = "documentation",
    other = "other",
  }

  export enum AttemptOutcome {
    success = "success",
    failed = "failed",
    partial = "partial",
  }

  export enum AnalyticsActorType {
    staff = "staff",
    guest = "guest",
    anonymous = "anonymous",
    system = "system",
  }

  // Prisma namespace augmentations for transaction client
  export namespace Prisma {
    export type TransactionClient = import("@prisma/client").PrismaClient;
    export type InputJsonValue = import("@prisma/client/runtime/client").InputJsonValue;
  }

  // Re-export PrismaClient for compatibility
  export class PrismaClient {
    [key: string]: unknown;
  }
}
